[CRITICAL]2021-05-28 16:21:26,548: agvApi send task, agvId=AGVdiniu cause a error: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
pid=14172, ppid=13760, tid=6116
Traceback (most recent call last):
  File "..\driver\seerAgv\agvApi.py", line 203, in task
    ret = _handle(agvId, API_PORT_TASK, type, data)
  File "..\driver\seerAgv\agvApi.py", line 252, in _handle
    result = _request(agvId, port, typeId, data)
  File "..\driver\seerAgv\agvApi.py", line 289, in _request
    result = sendCmd(agvId, buf, ip, port, type)
  File "..\driver\seerAgv\agvApi.py", line 297, in sendCmd
    _send(agvId,ip, port, buf.buf)
  File "..\driver\seerAgv\agvApi.py", line 381, in _send
    return tcpSocketLong.send(agvId,ip, port, buf)
  File "C:\Users\comba\Desktop\KLC\knowledgeCity\common\tcpSocketLong.py", line 136, in send
    raise e
  File "C:\Users\comba\Desktop\KLC\knowledgeCity\common\tcpSocketLong.py", line 131, in send
    c.send(sendData)
  File "C:\Users\comba\Desktop\KLC\knowledgeCity\common\tcpSocketLong.py", line 82, in send
    self._socket.send(sendData)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

