[INFO]2021-06-04 16:41:35,859: log files at C:\Users\comba\Desktop\KLC\knowledgeCity\common\log
[INFO]2021-06-04 16:41:35,860: find module agvCtrl.main_agv
[INFO]2021-06-04 16:41:35,860: find module agvDevice.main_agvDevice
[INFO]2021-06-04 16:41:35,860: find module alarm.main_alarm
[INFO]2021-06-04 16:41:35,861: find module auth.main_auth
[INFO]2021-06-04 16:41:35,861: find module autoCtrl.main_akmCtrl
[INFO]2021-06-04 16:41:35,861: find module door.main_door
[INFO]2021-06-04 16:41:35,863: find module elevator.main_elevator
[INFO]2021-06-04 16:41:35,863: find module feed.main_feed
[INFO]2021-06-04 16:41:35,864: find module remoteio.main_remoteio
[INFO]2021-06-04 16:41:35,864: import agvCtrl.main_agv
[INFO]2021-06-04 16:41:36,112: create lock <lock name:doorMgr.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x00000237575E47B0>>
[INFO]2021-06-04 16:41:36,113: create lock <lock name:door.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x00000237575E4918>>
[INFO]2021-06-04 16:41:36,160: create lock <lock name:timer.lock_2436714682688,<unlocked _thread.RLock object owner=0 count=0 at 0x000002375782F440>>
[ERROR]2021-06-04 16:41:36,176: mqtt is disabled
[INFO]2021-06-04 16:41:36,177: mqtt: subscribe [alarm/raise/+]
[INFO]2021-06-04 16:41:36,177: mqtt: subscribe [alarm/clear/+]
[INFO]2021-06-04 16:41:39,197: Mongodb connect to 127.0.0.1 port 27017
[INFO]2021-06-04 16:41:39,228: create lock <lock name:elevatorApi.tcp_lock,<unlocked _thread.RLock object owner=0 count=0 at 0x00000237579F8B48>>
[INFO]2021-06-04 16:41:39,230: create lock <lock name:elevatorApi.g_lock,<unlocked _thread.RLock object owner=0 count=0 at 0x00000237579F8788>>
[INFO]2021-06-04 16:41:39,231: create lock <lock name:elevatorMgr.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x00000237579F8300>>
[INFO]2021-06-04 16:41:39,239: create lock <lock name:agvserver,<unlocked _thread.RLock object owner=0 count=0 at 0x0000023757AFE710>>
[INFO]2021-06-04 16:41:39,387: create lock <lock name:mapMgr.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000023755DBC198>>
[INFO]2021-06-04 16:41:39,598: create lock <lock name:agvList.g_agvLock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000023757BCFE40>>
[INFO]2021-06-04 16:41:39,601: create lock <lock name:taskList.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000023757C18FD0>>
[INFO]2021-06-04 16:41:39,651: charge policy 0 , fix time
[INFO]2021-06-04 16:41:39,676: create lock <lock name:agvApi.g_lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000023757C8D1C0>>
[INFO]2021-06-04 16:41:40,113: start load map C:\Users\comba\Desktop\KLC\knowledgeCity\agvCtrl\projects\knowledgeCity\comba-ZSC-3F_0419.smap
[DEBUG]2021-06-04 16:41:40,190: elevator thread start
[INFO]2021-06-04 16:41:40,206: load map C:\Users\comba\Desktop\KLC\knowledgeCity\agvCtrl\projects\knowledgeCity\comba-ZSC-3F_0419.smap ,used 101 ms
[INFO]2021-06-04 16:41:40,214: start load map C:\Users\comba\Desktop\KLC\knowledgeCity\agvCtrl\projects\knowledgeCity\comba-ZSC-F1-F3.smap
[INFO]2021-06-04 16:41:40,357: load map C:\Users\comba\Desktop\KLC\knowledgeCity\agvCtrl\projects\knowledgeCity\comba-ZSC-F1-F3.smap ,used 150 ms
[INFO]2021-06-04 16:41:40,365: start load map C:\Users\comba\Desktop\KLC\knowledgeCity\agvCtrl\projects\knowledgeCity\comba-ZXC-3F.smap
[INFO]2021-06-04 16:41:40,440: load map C:\Users\comba\Desktop\KLC\knowledgeCity\agvCtrl\projects\knowledgeCity\comba-ZXC-3F.smap ,used 82 ms
[INFO]2021-06-04 16:41:40,448: start load map C:\Users\comba\Desktop\KLC\knowledgeCity\agvCtrl\projects\knowledgeCity\comba-ZXC-F3.smap
[INFO]2021-06-04 16:41:40,500: load map C:\Users\comba\Desktop\KLC\knowledgeCity\agvCtrl\projects\knowledgeCity\comba-ZXC-F3.smap ,used 58 ms
[INFO]2021-06-04 16:41:40,507: start load map C:\Users\comba\Desktop\KLC\knowledgeCity\agvCtrl\projects\knowledgeCity\office.smap
[INFO]2021-06-04 16:41:40,540: load map C:\Users\comba\Desktop\KLC\knowledgeCity\agvCtrl\projects\knowledgeCity\office.smap ,used 39 ms
[INFO]2021-06-04 16:41:40,544: import agvDevice.main_agvDevice
[INFO]2021-06-04 16:41:40,545: import alarm.main_alarm
[INFO]2021-06-04 16:41:40,545: import auth.main_auth
[INFO]2021-06-04 16:41:40,551: import autoCtrl.main_akmCtrl
[CRITICAL]2021-06-04 16:41:40,570: import main_akmCtrl failed, path: autoCtrl cause a error: inconsistent use of tabs and spaces in indentation (runTasks.py, line 793)
pid=10192, ppid=11192, tid=10936
Traceback (most recent call last):
  File "run_all.py", line 39, in findModule
    __import__(m[1])
  File "C:\Users\comba\Desktop\KLC\knowledgeCity\autoCtrl\main_akmCtrl.py", line 18, in <module>
    import deviceCtrl
  File "C:\Users\comba\Desktop\KLC\knowledgeCity\autoCtrl\deviceCtrl.py", line 22, in <module>
    import runTasks
  File "C:\Users\comba\Desktop\KLC\knowledgeCity\autoCtrl\runTasks.py", line 793
    self._moveAgv()
                  ^
TabError: inconsistent use of tabs and spaces in indentation

[CRITICAL]2021-06-04 16:41:40,573: import main_akmCtrl failed, path: autoCtrl ,cause inconsistent use of tabs and spaces in indentation (runTasks.py, line 793)
[INFO]2021-06-04 16:41:44,053: load agv file: C:\Users\comba\Desktop\KLC\knowledgeCity\agvCtrl/projects/knowledgeCity/agv.cfg
[INFO]2021-06-04 16:41:44,055: create lock <lock name:agvList.AGV01.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000023758104698>>
[DEBUG]2021-06-04 16:41:44,058: create aliveObj AGV01 AGV离线异常 timeout 300
[INFO]2021-06-04 16:41:44,059: AGV01 start agvList run thread
[INFO]2021-06-04 16:41:44,060: AGV01 start agvList run2 thread
[INFO]2021-06-04 16:41:44,061: create lock <lock name:agv.AGV01.lock_status,<unlocked _thread.RLock object owner=0 count=0 at 0x00000237581048F0>>
[DEBUG]2021-06-04 16:41:44,063: try connect AGV01 172.16.217.209:19204
[INFO]2021-06-04 16:41:44,064: create lock <lock name:agvList.AGVdiniu.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000023758104990>>
[DEBUG]2021-06-04 16:41:44,067: create aliveObj AGVdiniu AGV离线异常 timeout 300
[INFO]2021-06-04 16:41:44,068: AGVdiniu start agvList run thread
[INFO]2021-06-04 16:41:44,068: AGVdiniu start agvList run2 thread
[INFO]2021-06-04 16:41:44,068: create lock <lock name:agvList.AGVwuliao.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000023758104B20>>
[INFO]2021-06-04 16:41:44,069: create lock <lock name:agv.AGVdiniu.lock_status,<unlocked _thread.RLock object owner=0 count=0 at 0x0000023758104B70>>
[DEBUG]2021-06-04 16:41:44,071: try connect AGVdiniu 172.16.217.121:19204
[DEBUG]2021-06-04 16:41:44,072: create aliveObj AGVwuliao AGV离线异常 timeout 300
[INFO]2021-06-04 16:41:44,074: AGVwuliao start agvList run thread
[INFO]2021-06-04 16:41:44,074: AGVwuliao start agvList run2 thread
[INFO]2021-06-04 16:41:44,074: create lock <lock name:agvList.AGVchache.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000023758104DA0>>
[INFO]2021-06-04 16:41:44,074: create lock <lock name:agv.AGVwuliao.lock_status,<unlocked _thread.RLock object owner=0 count=0 at 0x0000023758104DF0>>
[DEBUG]2021-06-04 16:41:44,076: try connect AGVwuliao 172.16.217.211:19204
[DEBUG]2021-06-04 16:41:44,078: create aliveObj AGVchache AGV离线异常 timeout 300
[INFO]2021-06-04 16:41:44,078: AGVchache start agvList run thread
[INFO]2021-06-04 16:41:44,079: AGVchache start agvList run2 thread
[INFO]2021-06-04 16:41:44,154: create lock <lock name:agv.AGVchache.lock_status,<unlocked _thread.RLock object owner=0 count=0 at 0x000002375A280198>>
[DEBUG]2021-06-04 16:41:44,159: try connect AGVchache 172.16.217.213:19204
[INFO]2021-06-04 16:41:44,189: AGVchache connected 172.16.217.213 19204
[INFO]2021-06-04 16:41:44,192: create lock <lock name:agv.AGVchache.lock_ctrl,<unlocked _thread.RLock object owner=0 count=0 at 0x000002375A2801E8>>
[DEBUG]2021-06-04 16:41:44,196: try connect AGVchache 172.16.217.213:19205
[INFO]2021-06-04 16:41:44,274: AGVchache connected 172.16.217.213 19205
[INFO]2021-06-04 16:41:44,275: create lock <lock name:agv.AGVchache.lock_task,<unlocked _thread.RLock object owner=0 count=0 at 0x000002375A4A3170>>
[DEBUG]2021-06-04 16:41:44,276: try connect AGVchache 172.16.217.213:19206
[INFO]2021-06-04 16:41:44,300: AGVchache connected 172.16.217.213 19206
[INFO]2021-06-04 16:41:44,305: create lock <lock name:agv.AGVchache.lock_conf,<unlocked _thread.RLock object owner=0 count=0 at 0x000002375A4F6B20>>
[DEBUG]2021-06-04 16:41:44,318: try connect AGVchache 172.16.217.213:19207
[INFO]2021-06-04 16:41:44,381: AGVchache connected 172.16.217.213 19207
[INFO]2021-06-04 16:41:44,388: create lock <lock name:agv.AGVchache.lock_core,<unlocked _thread.RLock object owner=0 count=0 at 0x000002375A6E3C88>>
[DEBUG]2021-06-04 16:41:44,389: try connect AGVchache 172.16.217.213:19208
[INFO]2021-06-04 16:41:44,407: AGVchache connected 172.16.217.213 19208
[INFO]2021-06-04 16:41:44,412: create lock <lock name:agv.AGVchache.lock_other,<unlocked _thread.RLock object owner=0 count=0 at 0x000002375A734A08>>
[DEBUG]2021-06-04 16:41:44,418: try connect AGVchache 172.16.217.213:19210
[INFO]2021-06-04 16:41:44,451: AGVchache connected 172.16.217.213 19210
[INFO]2021-06-04 16:41:44,506: AGVchache current map comba-ZSC-F1-F3
[INFO]2021-06-04 16:41:44,526: AGVchache is online
[ERROR]2021-06-04 16:41:54,065: connect AGV01 failed timed out
[DEBUG]2021-06-04 16:41:54,066: try connect AGV01 172.16.217.209:19204
[ERROR]2021-06-04 16:41:54,071: connect AGVdiniu failed timed out
[DEBUG]2021-06-04 16:41:54,072: try connect AGVdiniu 172.16.217.121:19204
[ERROR]2021-06-04 16:41:54,077: connect AGVwuliao failed timed out
[DEBUG]2021-06-04 16:41:54,078: try connect AGVwuliao 172.16.217.211:19204
[ERROR]2021-06-04 16:42:04,068: connect AGV01 failed timed out
[INFO]2021-06-04 16:42:04,070: AGV01 checkLink failed 172.16.217.209 19204
[WARN]2021-06-04 16:42:04,070: agvThread.AGV01[tid:6688] <lock name:agv.AGV01.lock_status,<locked _thread.RLock object owner=6688 count=1 at 0x00000237581048F0>> ,hold 20007 ms
[INFO]2021-06-04 16:42:04,072: name=agvThread.AGV01, pid=10192, tid=6688
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[ERROR]2021-06-04 16:42:04,074: connect AGVdiniu failed timed out
[INFO]2021-06-04 16:42:04,075: AGVdiniu checkLink failed 172.16.217.121 19204
[WARN]2021-06-04 16:42:04,075: agvThread.AGVdiniu[tid:3560] <lock name:agv.AGVdiniu.lock_status,<locked _thread.RLock object owner=3560 count=1 at 0x0000023758104B70>> ,hold 20004 ms
[INFO]2021-06-04 16:42:04,077: name=agvThread.AGVdiniu, pid=10192, tid=3560
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[ERROR]2021-06-04 16:42:04,080: connect AGVwuliao failed timed out
[INFO]2021-06-04 16:42:04,080: AGVwuliao checkLink failed 172.16.217.211 19204
[WARN]2021-06-04 16:42:04,080: agvThread.AGVwuliao[tid:628] <lock name:agv.AGVwuliao.lock_status,<locked _thread.RLock object owner=628 count=1 at 0x0000023758104DF0>> ,hold 20004 ms
[INFO]2021-06-04 16:42:04,081: name=agvThread.AGVwuliao, pid=10192, tid=628
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-06-04 16:42:06,073: try connect AGV01 172.16.217.209:19204
[DEBUG]2021-06-04 16:42:06,078: try connect AGVdiniu 172.16.217.121:19204
[DEBUG]2021-06-04 16:42:06,083: try connect AGVwuliao 172.16.217.211:19204
[ERROR]2021-06-04 16:42:16,075: connect AGV01 failed timed out
[INFO]2021-06-04 16:42:16,078: AGV01 checkLink failed 172.16.217.209 19204
[WARN]2021-06-04 16:42:16,078: agvThread.AGV01[tid:6688] <lock name:agv.AGV01.lock_status,<locked _thread.RLock object owner=6688 count=1 at 0x00000237581048F0>> ,hold 10005 ms
[ERROR]2021-06-04 16:42:16,079: connect AGVdiniu failed timed out
[INFO]2021-06-04 16:42:16,080: name=agvThread.AGV01, pid=10192, tid=6688
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[INFO]2021-06-04 16:42:16,080: AGVdiniu checkLink failed 172.16.217.121 19204
[WARN]2021-06-04 16:42:16,081: agvThread.AGVdiniu[tid:3560] <lock name:agv.AGVdiniu.lock_status,<locked _thread.RLock object owner=3560 count=1 at 0x0000023758104B70>> ,hold 10003 ms
[INFO]2021-06-04 16:42:16,082: name=agvThread.AGVdiniu, pid=10192, tid=3560
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[ERROR]2021-06-04 16:42:16,084: connect AGVwuliao failed timed out
[INFO]2021-06-04 16:42:16,084: AGVwuliao checkLink failed 172.16.217.211 19204
[WARN]2021-06-04 16:42:16,085: agvThread.AGVwuliao[tid:628] <lock name:agv.AGVwuliao.lock_status,<locked _thread.RLock object owner=628 count=1 at 0x0000023758104DF0>> ,hold 10002 ms
[INFO]2021-06-04 16:42:16,086: name=agvThread.AGVwuliao, pid=10192, tid=628
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-06-04 16:42:18,082: try connect AGV01 172.16.217.209:19204
[DEBUG]2021-06-04 16:42:18,085: try connect AGVdiniu 172.16.217.121:19204
[DEBUG]2021-06-04 16:42:18,089: try connect AGVwuliao 172.16.217.211:19204
[ERROR]2021-06-04 16:42:28,083: connect AGV01 failed timed out
[ERROR]2021-06-04 16:42:28,086: connect AGVdiniu failed timed out
[INFO]2021-06-04 16:42:28,086: AGV01 checkLink failed 172.16.217.209 19204
[INFO]2021-06-04 16:42:28,088: AGVdiniu checkLink failed 172.16.217.121 19204
[WARN]2021-06-04 16:42:28,090: agvThread.AGV01[tid:6688] <lock name:agv.AGV01.lock_status,<locked _thread.RLock object owner=6688 count=1 at 0x00000237581048F0>> ,hold 10008 ms
[ERROR]2021-06-04 16:42:28,090: connect AGVwuliao failed timed out
[WARN]2021-06-04 16:42:28,092: agvThread.AGVdiniu[tid:3560] <lock name:agv.AGVdiniu.lock_status,<locked _thread.RLock object owner=3560 count=1 at 0x0000023758104B70>> ,hold 10007 ms
[INFO]2021-06-04 16:42:28,096: name=agvThread.AGV01, pid=10192, tid=6688
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[INFO]2021-06-04 16:42:28,097: AGVwuliao checkLink failed 172.16.217.211 19204
[INFO]2021-06-04 16:42:28,100: name=agvThread.AGVdiniu, pid=10192, tid=3560
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[WARN]2021-06-04 16:42:28,104: agvThread.AGVwuliao[tid:628] <lock name:agv.AGVwuliao.lock_status,<locked _thread.RLock object owner=628 count=1 at 0x0000023758104DF0>> ,hold 10015 ms
[INFO]2021-06-04 16:42:28,112: name=agvThread.AGVwuliao, pid=10192, tid=628
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-06-04 16:42:30,103: try connect AGV01 172.16.217.209:19204
[DEBUG]2021-06-04 16:42:30,110: try connect AGVdiniu 172.16.217.121:19204
[DEBUG]2021-06-04 16:42:30,116: try connect AGVwuliao 172.16.217.211:19204
[ERROR]2021-06-04 16:42:40,106: connect AGV01 failed timed out
[INFO]2021-06-04 16:42:40,108: AGV01 checkLink failed 172.16.217.209 19204
[WARN]2021-06-04 16:42:40,110: agvThread.AGV01[tid:6688] <lock name:agv.AGV01.lock_status,<locked _thread.RLock object owner=6688 count=1 at 0x00000237581048F0>> ,hold 10007 ms
[INFO]2021-06-04 16:42:40,112: name=agvThread.AGV01, pid=10192, tid=6688
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[ERROR]2021-06-04 16:42:40,113: connect AGVdiniu failed timed out
[INFO]2021-06-04 16:42:40,115: AGVdiniu checkLink failed 172.16.217.121 19204
[WARN]2021-06-04 16:42:40,117: agvThread.AGVdiniu[tid:3560] <lock name:agv.AGVdiniu.lock_status,<locked _thread.RLock object owner=3560 count=1 at 0x0000023758104B70>> ,hold 10006 ms
[ERROR]2021-06-04 16:42:40,120: connect AGVwuliao failed timed out
[INFO]2021-06-04 16:42:40,121: name=agvThread.AGVdiniu, pid=10192, tid=3560
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[INFO]2021-06-04 16:42:40,122: AGVwuliao checkLink failed 172.16.217.211 19204
[WARN]2021-06-04 16:42:40,125: agvThread.AGVwuliao[tid:628] <lock name:agv.AGVwuliao.lock_status,<locked _thread.RLock object owner=628 count=1 at 0x0000023758104DF0>> ,hold 10009 ms
[INFO]2021-06-04 16:42:40,127: name=agvThread.AGVwuliao, pid=10192, tid=628
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-06-04 16:42:42,115: try connect AGV01 172.16.217.209:19204
[DEBUG]2021-06-04 16:42:42,125: try connect AGVdiniu 172.16.217.121:19204
[DEBUG]2021-06-04 16:42:42,131: try connect AGVwuliao 172.16.217.211:19204
[ERROR]2021-06-04 16:42:52,117: connect AGV01 failed timed out
[INFO]2021-06-04 16:42:52,118: AGV01 checkLink failed 172.16.217.209 19204
[WARN]2021-06-04 16:42:52,119: agvThread.AGV01[tid:6688] <lock name:agv.AGV01.lock_status,<locked _thread.RLock object owner=6688 count=1 at 0x00000237581048F0>> ,hold 10004 ms
[INFO]2021-06-04 16:42:52,120: name=agvThread.AGV01, pid=10192, tid=6688
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[ERROR]2021-06-04 16:42:52,126: connect AGVdiniu failed timed out
[INFO]2021-06-04 16:42:52,127: AGVdiniu checkLink failed 172.16.217.121 19204
[WARN]2021-06-04 16:42:52,128: agvThread.AGVdiniu[tid:3560] <lock name:agv.AGVdiniu.lock_status,<locked _thread.RLock object owner=3560 count=1 at 0x0000023758104B70>> ,hold 10003 ms
[INFO]2021-06-04 16:42:52,129: name=agvThread.AGVdiniu, pid=10192, tid=3560
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[ERROR]2021-06-04 16:42:52,132: connect AGVwuliao failed timed out
[INFO]2021-06-04 16:42:52,132: AGVwuliao checkLink failed 172.16.217.211 19204
[WARN]2021-06-04 16:42:52,133: agvThread.AGVwuliao[tid:628] <lock name:agv.AGVwuliao.lock_status,<locked _thread.RLock object owner=628 count=1 at 0x0000023758104DF0>> ,hold 10002 ms
[INFO]2021-06-04 16:42:52,134: name=agvThread.AGVwuliao, pid=10192, tid=628
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-06-04 16:42:54,123: try connect AGV01 172.16.217.209:19204
[DEBUG]2021-06-04 16:42:54,131: try connect AGVdiniu 172.16.217.121:19204
[DEBUG]2021-06-04 16:42:54,136: try connect AGVwuliao 172.16.217.211:19204
[ERROR]2021-06-04 16:43:04,128: connect AGV01 failed timed out
[INFO]2021-06-04 16:43:04,129: AGV01 checkLink failed 172.16.217.209 19204
[WARN]2021-06-04 16:43:04,130: agvThread.AGV01[tid:6688] <lock name:agv.AGV01.lock_status,<locked _thread.RLock object owner=6688 count=1 at 0x00000237581048F0>> ,hold 10007 ms
[INFO]2021-06-04 16:43:04,131: name=agvThread.AGV01, pid=10192, tid=6688
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[ERROR]2021-06-04 16:43:04,134: connect AGVdiniu failed timed out
[INFO]2021-06-04 16:43:04,134: AGVdiniu checkLink failed 172.16.217.121 19204
[WARN]2021-06-04 16:43:04,135: agvThread.AGVdiniu[tid:3560] <lock name:agv.AGVdiniu.lock_status,<locked _thread.RLock object owner=3560 count=1 at 0x0000023758104B70>> ,hold 10004 ms
[INFO]2021-06-04 16:43:04,136: name=agvThread.AGVdiniu, pid=10192, tid=3560
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[ERROR]2021-06-04 16:43:04,139: connect AGVwuliao failed timed out
[INFO]2021-06-04 16:43:04,139: AGVwuliao checkLink failed 172.16.217.211 19204
[WARN]2021-06-04 16:43:04,140: agvThread.AGVwuliao[tid:628] <lock name:agv.AGVwuliao.lock_status,<locked _thread.RLock object owner=628 count=1 at 0x0000023758104DF0>> ,hold 10004 ms
[INFO]2021-06-04 16:43:04,141: name=agvThread.AGVwuliao, pid=10192, tid=628
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-06-04 16:43:06,133: try connect AGV01 172.16.217.209:19204
[DEBUG]2021-06-04 16:43:06,137: try connect AGVdiniu 172.16.217.121:19204
[DEBUG]2021-06-04 16:43:06,143: try connect AGVwuliao 172.16.217.211:19204
[ERROR]2021-06-04 16:43:16,135: connect AGV01 failed timed out
[INFO]2021-06-04 16:43:16,136: AGV01 checkLink failed 172.16.217.209 19204
[WARN]2021-06-04 16:43:16,137: agvThread.AGV01[tid:6688] <lock name:agv.AGV01.lock_status,<locked _thread.RLock object owner=6688 count=1 at 0x00000237581048F0>> ,hold 10004 ms
[ERROR]2021-06-04 16:43:16,139: connect AGVdiniu failed timed out
[INFO]2021-06-04 16:43:16,139: name=agvThread.AGV01, pid=10192, tid=6688
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[INFO]2021-06-04 16:43:16,139: AGVdiniu checkLink failed 172.16.217.121 19204
[WARN]2021-06-04 16:43:16,141: agvThread.AGVdiniu[tid:3560] <lock name:agv.AGVdiniu.lock_status,<locked _thread.RLock object owner=3560 count=1 at 0x0000023758104B70>> ,hold 10004 ms
[INFO]2021-06-04 16:43:16,143: name=agvThread.AGVdiniu, pid=10192, tid=3560
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[ERROR]2021-06-04 16:43:16,144: connect AGVwuliao failed timed out
[INFO]2021-06-04 16:43:16,146: AGVwuliao checkLink failed 172.16.217.211 19204
[WARN]2021-06-04 16:43:16,147: agvThread.AGVwuliao[tid:628] <lock name:agv.AGVwuliao.lock_status,<locked _thread.RLock object owner=628 count=1 at 0x0000023758104DF0>> ,hold 10004 ms
[INFO]2021-06-04 16:43:16,148: name=agvThread.AGVwuliao, pid=10192, tid=628
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-06-04 16:43:18,142: try connect AGV01 172.16.217.209:19204
[DEBUG]2021-06-04 16:43:18,146: try connect AGVdiniu 172.16.217.121:19204
[DEBUG]2021-06-04 16:43:18,150: try connect AGVwuliao 172.16.217.211:19204
[ERROR]2021-06-04 16:43:28,143: connect AGV01 failed timed out
[INFO]2021-06-04 16:43:28,144: AGV01 checkLink failed 172.16.217.209 19204
[ERROR]2021-06-04 16:43:28,146: connect AGVdiniu failed timed out
[WARN]2021-06-04 16:43:28,146: agvThread.AGV01[tid:6688] <lock name:agv.AGV01.lock_status,<locked _thread.RLock object owner=6688 count=1 at 0x00000237581048F0>> ,hold 10004 ms
[INFO]2021-06-04 16:43:28,147: AGVdiniu checkLink failed 172.16.217.121 19204
[INFO]2021-06-04 16:43:28,148: name=agvThread.AGV01, pid=10192, tid=6688
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[WARN]2021-06-04 16:43:28,148: agvThread.AGVdiniu[tid:3560] <lock name:agv.AGVdiniu.lock_status,<locked _thread.RLock object owner=3560 count=1 at 0x0000023758104B70>> ,hold 10002 ms
[ERROR]2021-06-04 16:43:28,150: connect AGVwuliao failed timed out
[INFO]2021-06-04 16:43:28,150: name=agvThread.AGVdiniu, pid=10192, tid=3560
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[INFO]2021-06-04 16:43:28,150: AGVwuliao checkLink failed 172.16.217.211 19204
[WARN]2021-06-04 16:43:28,153: agvThread.AGVwuliao[tid:628] <lock name:agv.AGVwuliao.lock_status,<locked _thread.RLock object owner=628 count=1 at 0x0000023758104DF0>> ,hold 10003 ms
[INFO]2021-06-04 16:43:28,155: name=agvThread.AGVwuliao, pid=10192, tid=628
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-06-04 16:43:30,150: try connect AGV01 172.16.217.209:19204
[DEBUG]2021-06-04 16:43:30,153: try connect AGVdiniu 172.16.217.121:19204
[DEBUG]2021-06-04 16:43:30,157: try connect AGVwuliao 172.16.217.211:19204
[ERROR]2021-06-04 16:43:40,152: connect AGV01 failed timed out
[INFO]2021-06-04 16:43:40,154: AGV01 checkLink failed 172.16.217.209 19204
[ERROR]2021-06-04 16:43:40,155: connect AGVdiniu failed timed out
[WARN]2021-06-04 16:43:40,155: agvThread.AGV01[tid:6688] <lock name:agv.AGV01.lock_status,<locked _thread.RLock object owner=6688 count=1 at 0x00000237581048F0>> ,hold 10005 ms
[INFO]2021-06-04 16:43:40,156: AGVdiniu checkLink failed 172.16.217.121 19204
[INFO]2021-06-04 16:43:40,157: name=agvThread.AGV01, pid=10192, tid=6688
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[WARN]2021-06-04 16:43:40,157: agvThread.AGVdiniu[tid:3560] <lock name:agv.AGVdiniu.lock_status,<locked _thread.RLock object owner=3560 count=1 at 0x0000023758104B70>> ,hold 10004 ms
[ERROR]2021-06-04 16:43:40,159: connect AGVwuliao failed timed out
[INFO]2021-06-04 16:43:40,159: name=agvThread.AGVdiniu, pid=10192, tid=3560
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[INFO]2021-06-04 16:43:40,159: AGVwuliao checkLink failed 172.16.217.211 19204
[WARN]2021-06-04 16:43:40,160: agvThread.AGVwuliao[tid:628] <lock name:agv.AGVwuliao.lock_status,<locked _thread.RLock object owner=628 count=1 at 0x0000023758104DF0>> ,hold 10003 ms
[INFO]2021-06-04 16:43:40,161: name=agvThread.AGVwuliao, pid=10192, tid=628
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-06-04 16:43:42,159: try connect AGV01 172.16.217.209:19204
[DEBUG]2021-06-04 16:43:42,160: try connect AGVdiniu 172.16.217.121:19204
[DEBUG]2021-06-04 16:43:42,162: try connect AGVwuliao 172.16.217.211:19204
[ERROR]2021-06-04 16:43:52,165: connect AGV01 failed timed out
[INFO]2021-06-04 16:43:52,166: AGV01 checkLink failed 172.16.217.209 19204
[WARN]2021-06-04 16:43:52,167: agvThread.AGV01[tid:6688] <lock name:agv.AGV01.lock_status,<locked _thread.RLock object owner=6688 count=1 at 0x00000237581048F0>> ,hold 10008 ms
[INFO]2021-06-04 16:43:52,168: name=agvThread.AGV01, pid=10192, tid=6688
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[ERROR]2021-06-04 16:43:52,168: connect AGVdiniu failed timed out
[INFO]2021-06-04 16:43:52,168: AGVdiniu checkLink failed 172.16.217.121 19204
[ERROR]2021-06-04 16:43:52,168: connect AGVwuliao failed timed out
[WARN]2021-06-04 16:43:52,168: agvThread.AGVdiniu[tid:3560] <lock name:agv.AGVdiniu.lock_status,<locked _thread.RLock object owner=3560 count=1 at 0x0000023758104B70>> ,hold 10008 ms
[INFO]2021-06-04 16:43:52,169: AGVwuliao checkLink failed 172.16.217.211 19204
[INFO]2021-06-04 16:43:52,169: name=agvThread.AGVdiniu, pid=10192, tid=3560
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[WARN]2021-06-04 16:43:52,169: agvThread.AGVwuliao[tid:628] <lock name:agv.AGVwuliao.lock_status,<locked _thread.RLock object owner=628 count=1 at 0x0000023758104DF0>> ,hold 10007 ms
[INFO]2021-06-04 16:43:52,171: name=agvThread.AGVwuliao, pid=10192, tid=628
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-06-04 16:43:54,169: try connect AGV01 172.16.217.209:19204
[DEBUG]2021-06-04 16:43:54,171: try connect AGVdiniu 172.16.217.121:19204
[DEBUG]2021-06-04 16:43:54,172: try connect AGVwuliao 172.16.217.211:19204
[ERROR]2021-06-04 16:44:04,170: connect AGV01 failed timed out
[INFO]2021-06-04 16:44:04,171: AGV01 checkLink failed 172.16.217.209 19204
[ERROR]2021-06-04 16:44:04,171: connect AGVdiniu failed timed out
[ERROR]2021-06-04 16:44:04,172: connect AGVwuliao failed timed out
[WARN]2021-06-04 16:44:04,172: agvThread.AGV01[tid:6688] <lock name:agv.AGV01.lock_status,<locked _thread.RLock object owner=6688 count=1 at 0x00000237581048F0>> ,hold 10003 ms
[INFO]2021-06-04 16:44:04,173: AGVdiniu checkLink failed 172.16.217.121 19204
[INFO]2021-06-04 16:44:04,173: AGVwuliao checkLink failed 172.16.217.211 19204
[INFO]2021-06-04 16:44:04,175: name=agvThread.AGV01, pid=10192, tid=6688
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[WARN]2021-06-04 16:44:04,175: agvThread.AGVdiniu[tid:3560] <lock name:agv.AGVdiniu.lock_status,<locked _thread.RLock object owner=3560 count=1 at 0x0000023758104B70>> ,hold 10004 ms
[WARN]2021-06-04 16:44:04,175: agvThread.AGVwuliao[tid:628] <lock name:agv.AGVwuliao.lock_status,<locked _thread.RLock object owner=628 count=1 at 0x0000023758104DF0>> ,hold 10003 ms
[INFO]2021-06-04 16:44:04,177: name=agvThread.AGVdiniu, pid=10192, tid=3560
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[INFO]2021-06-04 16:44:04,177: name=agvThread.AGVwuliao, pid=10192, tid=628
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-06-04 16:44:06,177: try connect AGV01 172.16.217.209:19204
[DEBUG]2021-06-04 16:44:06,179: try connect AGVwuliao 172.16.217.211:19204
[DEBUG]2021-06-04 16:44:06,179: try connect AGVdiniu 172.16.217.121:19204
[ERROR]2021-06-04 16:44:16,178: connect AGV01 failed timed out
[ERROR]2021-06-04 16:44:16,180: connect AGVwuliao failed timed out
[ERROR]2021-06-04 16:44:16,181: connect AGVdiniu failed timed out
[INFO]2021-06-04 16:44:16,181: AGV01 checkLink failed 172.16.217.209 19204
[INFO]2021-06-04 16:44:16,183: AGVwuliao checkLink failed 172.16.217.211 19204
[INFO]2021-06-04 16:44:16,185: AGVdiniu checkLink failed 172.16.217.121 19204
[WARN]2021-06-04 16:44:16,186: agvThread.AGV01[tid:6688] <lock name:agv.AGV01.lock_status,<locked _thread.RLock object owner=6688 count=1 at 0x00000237581048F0>> ,hold 10009 ms
[WARN]2021-06-04 16:44:16,188: agvThread.AGVwuliao[tid:628] <lock name:agv.AGVwuliao.lock_status,<locked _thread.RLock object owner=628 count=1 at 0x0000023758104DF0>> ,hold 10009 ms
[WARN]2021-06-04 16:44:16,190: agvThread.AGVdiniu[tid:3560] <lock name:agv.AGVdiniu.lock_status,<locked _thread.RLock object owner=3560 count=1 at 0x0000023758104B70>> ,hold 10011 ms
[INFO]2021-06-04 16:44:16,194: name=agvThread.AGV01, pid=10192, tid=6688
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[INFO]2021-06-04 16:44:16,195: name=agvThread.AGVwuliao, pid=10192, tid=628
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[INFO]2021-06-04 16:44:16,197: name=agvThread.AGVdiniu, pid=10192, tid=3560
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-06-04 16:44:18,200: try connect AGV01 172.16.217.209:19204
[DEBUG]2021-06-04 16:44:18,205: try connect AGVwuliao 172.16.217.211:19204
[DEBUG]2021-06-04 16:44:18,208: try connect AGVdiniu 172.16.217.121:19204
[ERROR]2021-06-04 16:44:28,202: connect AGV01 failed timed out
[INFO]2021-06-04 16:44:28,202: AGV01 checkLink failed 172.16.217.209 19204
[WARN]2021-06-04 16:44:28,203: agvThread.AGV01[tid:6688] <lock name:agv.AGV01.lock_status,<locked _thread.RLock object owner=6688 count=1 at 0x00000237581048F0>> ,hold 10003 ms
[INFO]2021-06-04 16:44:28,204: name=agvThread.AGV01, pid=10192, tid=6688
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[ERROR]2021-06-04 16:44:28,206: connect AGVwuliao failed timed out
[INFO]2021-06-04 16:44:28,206: AGVwuliao checkLink failed 172.16.217.211 19204
[WARN]2021-06-04 16:44:28,207: agvThread.AGVwuliao[tid:628] <lock name:agv.AGVwuliao.lock_status,<locked _thread.RLock object owner=628 count=1 at 0x0000023758104DF0>> ,hold 10002 ms
[INFO]2021-06-04 16:44:28,207: name=agvThread.AGVwuliao, pid=10192, tid=628
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[ERROR]2021-06-04 16:44:28,209: connect AGVdiniu failed timed out
[INFO]2021-06-04 16:44:28,209: AGVdiniu checkLink failed 172.16.217.121 19204
[WARN]2021-06-04 16:44:28,209: agvThread.AGVdiniu[tid:3560] <lock name:agv.AGVdiniu.lock_status,<locked _thread.RLock object owner=3560 count=1 at 0x0000023758104B70>> ,hold 10001 ms
[INFO]2021-06-04 16:44:28,210: name=agvThread.AGVdiniu, pid=10192, tid=3560
[01] File "C:/Users/comba/AppData/Local/Programs/Python/Python37/lib/threading.py", line 865, in run() 
[02] File "C:/Users/comba/Desktop/KLC/knowledgeCity/agvCtrl/agvList.py", line 582, in run() 
[03] File "../driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "../driver/seerAgv/agvApi.py", line 185, in checkLink() 
[05] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/lock.py", line 102, in release() 
[06] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 268, in getTrace() 
[07] File "C:/Users/comba/Desktop/KLC/knowledgeCity/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-06-04 16:44:30,206: try connect AGV01 172.16.217.209:19204
[DEBUG]2021-06-04 16:44:30,209: try connect AGVwuliao 172.16.217.211:19204
[DEBUG]2021-06-04 16:44:30,212: try connect AGVdiniu 172.16.217.121:19204
