[INFO]2021-02-21 14:12:10,931: log files at D:\akm\common\log
[INFO]2021-02-21 14:12:10,932: find module agvCtrl.main_agv
[INFO]2021-02-21 14:12:10,933: find module agvDevice.main_agvDevice
[INFO]2021-02-21 14:12:10,934: find module akmCtrl.main_akmCtrl
[INFO]2021-02-21 14:12:10,935: find module alarm.main_alarm
[INFO]2021-02-21 14:12:10,935: find module auth.main_auth
[INFO]2021-02-21 14:12:10,936: find module button.main_button
[INFO]2021-02-21 14:12:10,937: find module door.main_door
[INFO]2021-02-21 14:12:10,938: find module elevator.main_elevator
[INFO]2021-02-21 14:12:10,939: find module remoteio.main_remoteio
[INFO]2021-02-21 14:12:10,941: import agvCtrl.main_agv
[ERROR]2021-02-21 14:12:11,123: mongo db is disabled
[INFO]2021-02-21 14:12:11,592: create lock <lock name:doorMgr.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000017B76E1B6F0>>
[INFO]2021-02-21 14:12:11,597: create lock <lock name:door.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000017B76E2C0C0>>
[INFO]2021-02-21 14:12:11,773: create lock <lock name:timer.lock_1629791435504,<unlocked _thread.RLock object owner=0 count=0 at 0x0000017B7723BC60>>
[ERROR]2021-02-21 14:12:11,793: mqtt is disabled
[INFO]2021-02-21 14:12:11,797: mqtt: subscribe [alarm/raise/+]
[INFO]2021-02-21 14:12:11,799: mqtt: subscribe [alarm/clear/+]
[INFO]2021-02-21 14:12:11,889: create lock <lock name:elevatorMgr.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000017B772C1930>>
[WARN]2021-02-21 14:12:11,987: use mockAgvCtrl
[INFO]2021-02-21 14:12:12,003: create lock <lock name:mapMgr.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000017B753FEF00>>
[INFO]2021-02-21 14:12:12,471: create lock <lock name:agvList.g_agvLock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000017B77B6E7E0>>
[INFO]2021-02-21 14:12:12,503: create lock <lock name:taskList.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000017B7743D150>>
[INFO]2021-02-21 14:12:12,505: charge policy 1 , fix time
[INFO]2021-02-21 14:12:12,523: create lock <lock name:agvApi.g_lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000017B7743DFC0>>
[INFO]2021-02-21 14:12:14,590: start load map D:\akm\agvCtrl\projects\test\20190911_F1.smap
[DEBUG]2021-02-21 14:12:18,175: create aliveObj DOOR40 门控离线异常 timeout 60
[DEBUG]2021-02-21 14:12:18,178: create aliveObj DOOR41 门控离线异常 timeout 60
[DEBUG]2021-02-21 14:12:18,192: create aliveObj ELEVATOR03 电梯离线异常 timeout 30
[DEBUG]2021-02-21 14:12:18,194: create aliveObj ELEVATOR01 电梯离线异常 timeout 30
[DEBUG]2021-02-21 14:12:18,197: create aliveObj ELEVATOR02 电梯离线异常 timeout 30
[DEBUG]2021-02-21 14:12:18,204: elevator thread start
[INFO]2021-02-21 14:12:19,591: load map D:\akm\agvCtrl\projects\test\20190911_F1.smap ,used 5001 ms
[INFO]2021-02-21 14:12:19,593: start load map D:\akm\agvCtrl\projects\test\408.smap
[INFO]2021-02-21 14:12:19,866: load map D:\akm\agvCtrl\projects\test\408.smap ,used 273 ms
[INFO]2021-02-21 14:12:19,868: start load map D:\akm\agvCtrl\projects\test\510.smap
[INFO]2021-02-21 14:12:20,109: load map D:\akm\agvCtrl\projects\test\510.smap ,used 240 ms
[INFO]2021-02-21 14:12:20,110: start load map D:\akm\agvCtrl\projects\test\8-222.smap
[INFO]2021-02-21 14:12:20,562: load map D:\akm\agvCtrl\projects\test\8-222.smap ,used 452 ms
[INFO]2021-02-21 14:12:20,564: start load map D:\akm\agvCtrl\projects\test\akmsmt.smap
[INFO]2021-02-21 14:12:21,239: load map D:\akm\agvCtrl\projects\test\akmsmt.smap ,used 675 ms
[INFO]2021-02-21 14:12:21,242: start load map D:\akm\agvCtrl\projects\test\akmsmtMap.smap
[INFO]2021-02-21 14:12:23,509: load map D:\akm\agvCtrl\projects\test\akmsmtMap.smap ,used 2267 ms
[INFO]2021-02-21 14:12:23,512: start load map D:\akm\agvCtrl\projects\test\bell.smap
[INFO]2021-02-21 14:12:23,850: load map D:\akm\agvCtrl\projects\test\bell.smap ,used 339 ms
[INFO]2021-02-21 14:12:23,852: start load map D:\akm\agvCtrl\projects\test\big.smap
[INFO]2021-02-21 14:12:57,796: load map D:\akm\agvCtrl\projects\test\big.smap ,used 33944 ms
[INFO]2021-02-21 14:12:57,798: start load map D:\akm\agvCtrl\projects\test\desai-all-20191223.smap
[INFO]2021-02-21 14:13:06,822: load map D:\akm\agvCtrl\projects\test\desai-all-20191223.smap ,used 9024 ms
[INFO]2021-02-21 14:13:06,825: start load map D:\akm\agvCtrl\projects\test\fp-neiwei.smap
[INFO]2021-02-21 14:13:52,911: load map D:\akm\agvCtrl\projects\test\fp-neiwei.smap ,used 46086 ms
[INFO]2021-02-21 14:13:52,912: start load map D:\akm\agvCtrl\projects\test\fp20190712-1.smap
[DEBUG]2021-02-21 14:14:15,116: create aliveObj DOOR13 门控离线异常 timeout 60
[DEBUG]2021-02-21 14:14:15,117: create aliveObj DOOR23 门控离线异常 timeout 60
[DEBUG]2021-02-21 14:14:15,118: create aliveObj DOOR08 门控离线异常 timeout 60
[DEBUG]2021-02-21 14:14:15,119: create aliveObj DOOR09 门控离线异常 timeout 60
[DEBUG]2021-02-21 14:14:15,120: create aliveObj DOOR15 门控离线异常 timeout 60
[DEBUG]2021-02-21 14:14:15,121: create aliveObj DOOR07 门控离线异常 timeout 60
[DEBUG]2021-02-21 14:14:15,122: create aliveObj DOOR04 门控离线异常 timeout 60
[DEBUG]2021-02-21 14:14:15,123: create aliveObj DOOR06 门控离线异常 timeout 60
[DEBUG]2021-02-21 14:14:15,125: create aliveObj DOOR17 门控离线异常 timeout 60
[DEBUG]2021-02-21 14:14:15,127: create aliveObj DOOR18 门控离线异常 timeout 60
[DEBUG]2021-02-21 14:14:15,129: create aliveObj DOOR20 门控离线异常 timeout 60
[DEBUG]2021-02-21 14:14:15,130: create aliveObj DOOR25 门控离线异常 timeout 60
[DEBUG]2021-02-21 14:14:15,131: create aliveObj DOOR27 门控离线异常 timeout 60
[INFO]2021-02-21 14:14:53,170: load map D:\akm\agvCtrl\projects\test\fp20190712-1.smap ,used 60258 ms
[INFO]2021-02-21 14:14:53,172: start load map D:\akm\agvCtrl\projects\test\shuqin.smap
[INFO]2021-02-21 14:14:53,587: load map D:\akm\agvCtrl\projects\test\shuqin.smap ,used 415 ms
[INFO]2021-02-21 14:14:53,588: start load map D:\akm\agvCtrl\projects\test\test430.smap
[INFO]2021-02-21 14:14:53,893: load map D:\akm\agvCtrl\projects\test\test430.smap ,used 305 ms
[INFO]2021-02-21 14:14:53,894: start load map D:\akm\agvCtrl\projects\test\testdesay.smap
[INFO]2021-02-21 14:14:54,190: load map D:\akm\agvCtrl\projects\test\testdesay.smap ,used 295 ms
[INFO]2021-02-21 14:14:54,192: start load map D:\akm\agvCtrl\projects\test\testmap.smap
[INFO]2021-02-21 14:14:54,575: load map D:\akm\agvCtrl\projects\test\testmap.smap ,used 384 ms
[INFO]2021-02-21 14:14:54,576: start load map D:\akm\agvCtrl\projects\test\testscada.smap
[INFO]2021-02-21 14:14:55,085: load map D:\akm\agvCtrl\projects\test\testscada.smap ,used 509 ms
[WARN]2021-02-21 14:14:55,087: MainThread[tid:7408] <lock name:mapMgr.lock,<locked _thread.RLock object owner=7408 count=1 at 0x0000017B753FEF00>> ,hold 162561 ms
[INFO]2021-02-21 14:14:55,089: name=MainThread, pid=6968, tid=7408
[01] File "D:/akm/common/run_all.py", line 57, in <module>() 
[02] File "D:/akm/common/run_all.py", line 39, in findModule() 
[03] File "<frozen importlib._bootstrap>", line 991, in _find_and_load() 
[04] File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked() 
[05] File "<frozen importlib._bootstrap>", line 671, in _load_unlocked() 
[06] File "<frozen importlib._bootstrap_external>", line 783, in exec_module() 
[07] File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed() 
[08] File "D:/akm/agvCtrl/main_agv.py", line 22, in <module>() 
[09] File "D:/akm/common/lock.py", line 124, in _call() 
[10] File "D:/akm/common/lock.py", line 102, in release() 
[11] File "D:/akm/common/enhance.py", line 268, in getTrace() 
[12] File "D:/akm/common/enhance.py", line 248, in getThreadStack()
[INFO]2021-02-21 14:14:55,094: import agvDevice.main_agvDevice
[INFO]2021-02-21 14:14:55,095: import akmCtrl.main_akmCtrl
[INFO]2021-02-21 14:14:55,176: create lock <lock name:agvApi.g_lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000017B0ADCE360>>
[INFO]2021-02-21 14:14:55,252: create lock <lock name:IOAlarm.s_lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000017B083C10C0>>
[INFO]2021-02-21 14:14:55,318: import alarm.main_alarm
[INFO]2021-02-21 14:14:55,319: import auth.main_auth
[DEBUG]2021-02-21 14:14:55,332: create aliveObj load009 远程控制IO离线异常 timeout 60
[DEBUG]2021-02-21 14:14:55,335: create aliveObj unload009 远程控制IO离线异常 timeout 60
[DEBUG]2021-02-21 14:14:55,337: create aliveObj load0010 远程控制IO离线异常 timeout 60
[DEBUG]2021-02-21 14:14:55,341: create aliveObj unload0010 远程控制IO离线异常 timeout 60
[DEBUG]2021-02-21 14:14:55,344: create aliveObj ZLAN01 远程控制IO离线异常 timeout 60
[DEBUG]2021-02-21 14:14:55,346: create aliveObj ZLAN02 远程控制IO离线异常 timeout 60
[DEBUG]2021-02-21 14:14:55,348: create aliveObj ZLAN03 远程控制IO离线异常 timeout 60
[DEBUG]2021-02-21 14:14:55,350: create aliveObj ZLAN04 远程控制IO离线异常 timeout 60
[DEBUG]2021-02-21 14:14:55,351: create aliveObj ZLAN05 远程控制IO离线异常 timeout 60
[DEBUG]2021-02-21 14:14:55,352: create aliveObj ZLANTEST 远程控制IO离线异常 timeout 60
[INFO]2021-02-21 14:14:55,980: import button.main_button
[INFO]2021-02-21 14:14:56,028: import door.main_door
[INFO]2021-02-21 14:14:56,061: import elevator.main_elevator
[INFO]2021-02-21 14:14:56,137: create lock <lock name:elevatorApi.g_lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000017B0910EE40>>
[INFO]2021-02-21 14:14:56,139: import remoteio.main_remoteio
[SUCC]2021-02-21 14:14:56,201: utility start, pid=6968, ppid=3000
[DEBUG]2021-02-21 14:14:56,202: start timer
[INFO]2021-02-21 14:14:56,204: load agv file: D:\akm\agvCtrl/projects/test/agv.cfg
[INFO]2021-02-21 14:14:56,205: create lock <lock name:agvList.agv71.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000017B09126AB0>>
[DEBUG]2021-02-21 14:14:56,207: create aliveObj agv71 AGV离线异常 timeout 300
[INFO]2021-02-21 14:14:56,210: agv71 start agvList run thread
[INFO]2021-02-21 14:14:56,210: agv71 start agvList run2 thread
[INFO]2021-02-21 14:14:56,211: create lock <lock name:agvList.agv72.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000017B0912B5D0>>
[INFO]2021-02-21 14:14:56,212: agv71 current map testdesay
[DEBUG]2021-02-21 14:14:56,214: create aliveObj agv72 AGV离线异常 timeout 300
[INFO]2021-02-21 14:14:56,215: agv71 is online
[INFO]2021-02-21 14:14:56,216: agv72 start agvList run thread
[INFO]2021-02-21 14:14:56,217: agv72 start agvList run2 thread
[INFO]2021-02-21 14:14:56,217: create lock <lock name:agvList.agv73.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000017B0912BCF0>>
[INFO]2021-02-21 14:14:56,219: agv72 current map testdesay
[DEBUG]2021-02-21 14:14:56,221: create aliveObj agv73 AGV离线异常 timeout 300
[INFO]2021-02-21 14:14:56,222: agv72 is online
[INFO]2021-02-21 14:14:56,226: agv73 start agvList run thread
[INFO]2021-02-21 14:14:56,227: agv73 start agvList run2 thread
[INFO]2021-02-21 14:14:56,227: startCharge is false
[INFO]2021-02-21 14:14:56,229: agv73 current map testdesay
[WARN]2021-02-21 14:14:56,229: Local server start! version 3.8.0, path D:\akm\common, pid 6968
[INFO]2021-02-21 14:14:56,233: agv73 is online
[INFO]2021-02-21 14:14:56,234: add_ignore: taskStatus
[DEBUG]2021-02-21 14:15:01,237: GET: http://127.0.0.1:8999/api/agv/init?appName=akmTask addr: 127.0.0.1
[INFO]2021-02-21 14:15:01,239: akmTask init client agvApi
[DEBUG]2021-02-21 14:15:01,243: used 5ms 200 OK application/json;charset=utf-8, GET: http://127.0.0.1:8999/api/agv/init?appName=akmTask
[CRITICAL]2021-02-21 14:15:34,882: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6031fa65d86d5d12889a2519, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[WARN]2021-02-21 14:15:34,950: timer_thread[tid:5724] <locked _thread.RLock object owner=5724 count=1 at 0x0000017B0ADA2360> ,hold 38719 ms
[INFO]2021-02-21 14:15:35,014: name=timer_thread, pid=6968, tid=5724
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/akm/common/mytimer.py", line 113, in _loop() 
[03] File "D:/akm/common/lock.py", line 124, in _call() 
[04] File "D:/akm/common/lock.py", line 102, in release() 
[05] File "D:/akm/common/enhance.py", line 268, in getTrace() 
[06] File "D:/akm/common/enhance.py", line 248, in getThreadStack()
[CRITICAL]2021-02-21 14:15:35,083: invoke timer func<function lock.<locals>.call.<locals>._call at 0x0000017B083D3430> cause a error: 'NoneType' object is not subscriptable
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\common\lock.py", line 122, in _call
    return func(*p,**pp)
  File "D:\akm\akmCtrl\runTasks.py", line 121, in run
    db.delete_many("u_agv_payload", '')
  File "D:\akm\common\mongodb.py", line 534, in __call
    r = func(*p,**pp)
  File "D:\akm\common\mongodb.py", line 104, in delete_many
    return self._get_db()[table].remove()
TypeError: 'NoneType' object is not subscriptable

[CRITICAL]2021-02-21 14:16:08,378: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6031fa87d86d5d12889a251a, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:16:08,450: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 14:16:09,493: startCharge is false
[CRITICAL]2021-02-21 14:16:42,979: Connect mongodb error! cause a error: 172.16.65.28:27017: [WinError 10053] 你的主机中的软件中止了一个已建立的连接。, Timeout: 30s, Topology Description: <TopologyDescription id: 6031faa9d86d5d12889a251b, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('172.16.65.28:27017: [WinError 10053] 你的主机中的软件中止了一个已建立的连接。')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:16:43,059: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 14:17:16,337: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6031facbd86d5d12889a251c, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:17:16,388: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 14:17:17,431: startCharge is false
[CRITICAL]2021-02-21 14:17:50,691: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6031faedd86d5d12889a251d, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:17:50,749: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 14:18:24,062: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6031fb0ed86d5d12889a251e, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:18:24,127: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 14:18:25,160: startCharge is false
[CRITICAL]2021-02-21 14:18:58,426: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6031fb31d86d5d12889a251f, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:18:58,480: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 14:19:31,745: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6031fb52d86d5d12889a2520, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:19:31,801: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 14:19:32,839: startCharge is false
[CRITICAL]2021-02-21 14:20:06,102: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6031fb74d86d5d12889a2521, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:20:06,165: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 14:20:39,470: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6031fb96d86d5d12889a2522, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:20:39,560: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 14:20:40,603: startCharge is false
[CRITICAL]2021-02-21 14:21:13,895: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6031fbb8d86d5d12889a2523, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:21:13,958: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 14:21:47,304: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6031fbdad86d5d12889a2524, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:21:47,387: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 14:21:48,423: startCharge is false
[CRITICAL]2021-02-21 14:22:21,638: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6031fbfcd86d5d12889a2525, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:22:21,697: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 14:22:54,996: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6031fc1dd86d5d12889a2526, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:22:55,060: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 14:22:56,098: startCharge is false
[CRITICAL]2021-02-21 14:23:29,401: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6031fc40d86d5d12889a2527, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:23:29,533: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 14:24:02,797: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6031fc61d86d5d12889a2528, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:24:02,883: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 14:24:03,944: startCharge is false
[CRITICAL]2021-02-21 14:24:37,242: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6031fc83d86d5d12889a2529, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:24:37,301: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 14:25:10,749: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6031fca5d86d5d12889a252a, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:25:10,836: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 14:25:11,936: startCharge is false
[CRITICAL]2021-02-21 14:25:45,421: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6031fcc7d86d5d12889a252b, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:25:45,476: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 14:26:18,815: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6031fce9d86d5d12889a252c, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:26:18,893: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 14:26:19,932: startCharge is false
[CRITICAL]2021-02-21 14:26:53,229: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6031fd0bd86d5d12889a252d, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:26:53,310: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 14:27:26,600: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6031fd2dd86d5d12889a252e, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:27:26,664: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 14:27:27,711: startCharge is false
[CRITICAL]2021-02-21 14:28:00,926: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6031fd4fd86d5d12889a252f, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:28:00,995: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 14:28:34,301: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6031fd71d86d5d12889a2530, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:28:34,365: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 14:28:35,404: startCharge is false
[CRITICAL]2021-02-21 14:29:08,660: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6031fd93d86d5d12889a2531, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:29:08,725: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 14:29:42,014: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6031fdb4d86d5d12889a2532, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:29:42,084: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 14:29:43,124: startCharge is false
[CRITICAL]2021-02-21 14:30:16,375: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6031fdd7d86d5d12889a2533, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:30:16,443: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 14:30:49,738: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6031fdf8d86d5d12889a2534, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:30:49,821: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 14:30:50,850: startCharge is false
[CRITICAL]2021-02-21 14:31:24,279: Connect mongodb error! cause a error: 172.16.65.28:27017: [WinError 10065] 套接字操作尝试一个无法连接的主机。, Timeout: 30s, Topology Description: <TopologyDescription id: 6031fe1ad86d5d12889a2535, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('172.16.65.28:27017: [WinError 10065] 套接字操作尝试一个无法连接的主机。')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:31:24,382: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 14:31:57,571: Connect mongodb error! cause a error: 172.16.65.28:27017: [WinError 10065] 套接字操作尝试一个无法连接的主机。, Timeout: 30s, Topology Description: <TopologyDescription id: 6031fe3cd86d5d12889a2536, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('172.16.65.28:27017: [WinError 10065] 套接字操作尝试一个无法连接的主机。')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:31:57,679: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 14:31:58,713: startCharge is false
[CRITICAL]2021-02-21 14:32:32,005: Connect mongodb error! cause a error: 172.16.65.28:27017: [WinError 10065] 套接字操作尝试一个无法连接的主机。, Timeout: 30s, Topology Description: <TopologyDescription id: 6031fe5ed86d5d12889a2537, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('172.16.65.28:27017: [WinError 10065] 套接字操作尝试一个无法连接的主机。')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:32:32,095: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 14:33:05,513: Connect mongodb error! cause a error: 172.16.65.28:27017: [WinError 10065] 套接字操作尝试一个无法连接的主机。, Timeout: 30s, Topology Description: <TopologyDescription id: 6031fe80d86d5d12889a2538, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('172.16.65.28:27017: [WinError 10065] 套接字操作尝试一个无法连接的主机。')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:33:05,583: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 14:33:06,626: startCharge is false
[CRITICAL]2021-02-21 14:33:39,832: Connect mongodb error! cause a error: 172.16.65.28:27017: [WinError 10065] 套接字操作尝试一个无法连接的主机。, Timeout: 30s, Topology Description: <TopologyDescription id: 6031fea2d86d5d12889a2539, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('172.16.65.28:27017: [WinError 10065] 套接字操作尝试一个无法连接的主机。')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:33:39,915: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 14:34:13,249: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6031fec3d86d5d12889a253a, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:34:13,295: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 14:34:14,355: startCharge is false
[CRITICAL]2021-02-21 14:34:47,648: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6031fee6d86d5d12889a253b, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:34:47,758: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 14:35:21,357: Connect mongodb error! cause a error: 172.16.65.28:27017: [WinError 10065] 套接字操作尝试一个无法连接的主机。, Timeout: 30s, Topology Description: <TopologyDescription id: 6031ff07d86d5d12889a253c, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('172.16.65.28:27017: [WinError 10065] 套接字操作尝试一个无法连接的主机。')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:35:21,422: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 14:35:22,490: startCharge is false
[CRITICAL]2021-02-21 14:35:55,776: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6031ff2ad86d5d12889a253d, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:35:55,863: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 14:36:29,383: Connect mongodb error! cause a error: 172.16.65.28:27017: [WinError 10053] 你的主机中的软件中止了一个已建立的连接。, Timeout: 30s, Topology Description: <TopologyDescription id: 6031ff4bd86d5d12889a253e, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('172.16.65.28:27017: [WinError 10053] 你的主机中的软件中止了一个已建立的连接。')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:36:29,459: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 14:36:30,512: startCharge is false
[CRITICAL]2021-02-21 14:37:03,841: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6031ff6ed86d5d12889a253f, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:37:03,913: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 14:37:37,174: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6031ff8fd86d5d12889a2540, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:37:37,232: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 14:37:38,262: startCharge is false
[CRITICAL]2021-02-21 14:38:11,602: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6031ffb2d86d5d12889a2541, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:38:11,673: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 14:38:45,019: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6031ffd3d86d5d12889a2542, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:38:45,085: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 14:38:46,132: startCharge is false
[CRITICAL]2021-02-21 14:39:19,399: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6031fff6d86d5d12889a2543, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:39:19,495: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 14:39:52,911: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 60320017d86d5d12889a2544, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:39:53,011: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 14:39:54,052: startCharge is false
[CRITICAL]2021-02-21 14:40:27,469: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6032003ad86d5d12889a2545, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:40:27,557: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 14:41:00,902: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6032005bd86d5d12889a2546, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:41:00,975: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 14:41:02,024: startCharge is false
[CRITICAL]2021-02-21 14:41:35,355: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6032007ed86d5d12889a2547, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:41:35,401: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 14:42:08,658: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6032009fd86d5d12889a2548, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:42:08,736: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 14:42:09,780: startCharge is false
[CRITICAL]2021-02-21 14:42:43,175: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 603200c1d86d5d12889a2549, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:42:43,260: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 14:43:16,674: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 603200e3d86d5d12889a254a, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:43:16,741: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 14:43:17,787: startCharge is false
[CRITICAL]2021-02-21 14:43:51,060: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 60320105d86d5d12889a254b, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:43:51,127: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 14:44:24,444: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 60320127d86d5d12889a254c, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:44:24,522: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 14:44:25,572: startCharge is false
[CRITICAL]2021-02-21 14:44:58,888: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 60320149d86d5d12889a254d, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:44:58,966: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 14:45:32,216: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6032016bd86d5d12889a254e, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:45:32,295: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 14:45:33,376: startCharge is false
[CRITICAL]2021-02-21 14:46:06,761: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6032018dd86d5d12889a254f, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:46:06,832: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 14:46:40,172: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 603201aed86d5d12889a2550, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:46:40,256: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 14:46:41,295: startCharge is false
[CRITICAL]2021-02-21 14:47:14,649: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 603201d1d86d5d12889a2551, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:47:14,723: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 14:47:48,206: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 603201f2d86d5d12889a2552, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:47:48,301: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 14:47:49,363: startCharge is false
[CRITICAL]2021-02-21 14:48:22,654: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 60320215d86d5d12889a2553, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:48:22,738: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 14:48:55,988: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 60320236d86d5d12889a2554, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:48:56,078: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 14:48:57,162: startCharge is false
[CRITICAL]2021-02-21 14:49:30,488: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 60320259d86d5d12889a2555, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:49:30,547: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 14:50:03,837: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6032027ad86d5d12889a2556, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:50:03,906: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 14:50:04,965: startCharge is false
[CRITICAL]2021-02-21 14:50:38,253: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6032029cd86d5d12889a2557, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:50:38,317: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 14:51:11,663: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 603202bed86d5d12889a2558, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:51:11,734: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 14:51:12,773: startCharge is false
[CRITICAL]2021-02-21 14:51:46,075: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 603202e0d86d5d12889a2559, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:51:46,143: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 14:52:19,414: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 60320302d86d5d12889a255a, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:52:19,489: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 14:52:20,529: startCharge is false
[CRITICAL]2021-02-21 14:52:53,817: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 60320324d86d5d12889a255b, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:52:53,931: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 14:53:27,224: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 60320345d86d5d12889a255c, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:53:27,304: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 14:53:28,393: startCharge is false
[CRITICAL]2021-02-21 14:54:01,668: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 60320368d86d5d12889a255d, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:54:01,732: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 14:54:35,100: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 60320389d86d5d12889a255e, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:54:35,158: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 14:54:36,195: startCharge is false
[CRITICAL]2021-02-21 14:55:09,656: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 603203acd86d5d12889a255f, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:55:09,742: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 14:55:43,009: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 603203cdd86d5d12889a2560, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:55:43,094: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 14:55:44,192: startCharge is false
[CRITICAL]2021-02-21 14:56:17,503: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 603203f0d86d5d12889a2561, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:56:17,552: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 14:56:50,879: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 60320411d86d5d12889a2562, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:56:50,968: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 14:56:52,006: startCharge is false
[CRITICAL]2021-02-21 14:57:25,370: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 60320434d86d5d12889a2563, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:57:25,458: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 14:57:58,875: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 60320455d86d5d12889a2564, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:57:58,992: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 14:58:00,041: startCharge is false
[CRITICAL]2021-02-21 14:58:33,378: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 60320478d86d5d12889a2565, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:58:33,417: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 14:59:06,652: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 60320499d86d5d12889a2566, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:59:06,727: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 14:59:07,788: startCharge is false
[CRITICAL]2021-02-21 14:59:41,156: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 603204bbd86d5d12889a2567, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 14:59:41,229: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 15:00:14,550: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 603204ddd86d5d12889a2568, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 15:00:14,622: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 15:00:15,671: startCharge is false
[CRITICAL]2021-02-21 15:00:49,070: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 603204ffd86d5d12889a2569, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 15:00:49,139: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 15:01:22,507: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 60320521d86d5d12889a256a, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 15:01:22,579: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 15:01:23,620: startCharge is false
[CRITICAL]2021-02-21 15:01:56,894: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 60320543d86d5d12889a256b, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 15:01:56,951: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 15:02:30,360: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 60320565d86d5d12889a256c, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 15:02:30,434: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 15:02:31,498: startCharge is false
[CRITICAL]2021-02-21 15:03:04,845: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 60320587d86d5d12889a256d, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 15:03:04,927: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 15:03:38,241: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 603205a8d86d5d12889a256e, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 15:03:38,330: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 15:03:39,403: startCharge is false
[CRITICAL]2021-02-21 15:04:12,697: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 603205cbd86d5d12889a256f, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 15:04:12,776: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 15:04:46,104: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 603205ecd86d5d12889a2570, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 15:04:46,166: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 15:04:47,215: startCharge is false
[CRITICAL]2021-02-21 15:05:20,558: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6032060fd86d5d12889a2571, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 15:05:20,636: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 15:05:53,885: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 60320630d86d5d12889a2572, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 15:05:53,954: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 15:05:54,993: startCharge is false
[CRITICAL]2021-02-21 15:06:28,517: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 60320653d86d5d12889a2573, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 15:06:28,577: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 15:07:01,803: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 60320674d86d5d12889a2574, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 15:07:01,876: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 15:07:02,913: startCharge is false
[CRITICAL]2021-02-21 15:07:36,263: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 60320696d86d5d12889a2575, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 15:07:36,330: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 15:08:09,794: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 603206b8d86d5d12889a2576, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 15:08:09,890: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 15:08:10,941: startCharge is false
[CRITICAL]2021-02-21 15:08:44,251: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 603206dad86d5d12889a2577, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 15:08:44,333: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 15:09:17,725: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 603206fcd86d5d12889a2578, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 15:09:17,817: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 15:09:18,856: startCharge is false
[CRITICAL]2021-02-21 15:09:52,160: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6032071ed86d5d12889a2579, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 15:09:52,214: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 15:10:25,518: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 60320740d86d5d12889a257a, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 15:10:25,621: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 15:10:26,660: startCharge is false
[CRITICAL]2021-02-21 15:10:59,933: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 60320762d86d5d12889a257b, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 15:11:00,016: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 15:11:33,391: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 60320784d86d5d12889a257c, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 15:11:33,467: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 15:11:34,513: startCharge is false
[CRITICAL]2021-02-21 15:12:07,795: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 603207a6d86d5d12889a257d, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 15:12:07,879: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 15:12:41,163: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 603207c7d86d5d12889a257e, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 15:12:41,221: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 15:12:42,270: startCharge is false
[CRITICAL]2021-02-21 15:13:15,677: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 603207ead86d5d12889a257f, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 15:13:15,756: invoke timer func<function _monitorDevices at 0x0000017B083CF820> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 52, in _monitorDevices
    devices = _loadDevices()
  File "D:\akm\akmCtrl\deviceCtrl.py", line 105, in _loadDevices
    ds = db.find("u_line_info")
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2021-02-21 15:13:49,067: Connect mongodb error! cause a error: 172.16.65.28:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6032080bd86d5d12889a2580, topology_type: Single, servers: [<ServerDescription ('172.16.65.28', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('172.16.65.28:27017: timed out')>]>
pid=6968, ppid=3000, tid=5724

[CRITICAL]2021-02-21 15:13:49,158: invoke timer func<function _loadDevicesAlarm at 0x0000017B083CF940> cause a error: mongodb is not connected
pid=6968, ppid=3000, tid=5724
Traceback (most recent call last):
  File "D:\akm\common\mytimer.py", line 113, in _loop
    v.func(*v.args)
  File "D:\akm\akmCtrl\deviceCtrl.py", line 127, in _loadDevicesAlarm
    ds = db.find("r_alarm", { "typeId": {"$in":[39998]}, "domain": "agv"})
  File "D:\akm\common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[INFO]2021-02-21 15:13:50,195: startCharge is false
