[CRITICAL]2020-04-21 14:37:24,609: Connect mongodb error! cause a error: 192.168.5.137:27017: timed out
pid=20796, ppid=19200, tid=1280

[CRITICAL]2020-04-21 14:37:24,618: update task error: cause a error: mongodb is not connected
pid=20796, ppid=19200, tid=1280
Traceback (most recent call last):
  File "E:/python_work/akm/akmCtrl/taskUI.py", line 150, in autoUpdateTask
    self.updateTaskBydb()
  File "E:/python_work/akm/akmCtrl/taskUI.py", line 128, in updateTaskBydb
    tasks = getAkmTask()
  File "E:/python_work/akm/akmCtrl/taskUI.py", line 160, in getAkmTask
    ds = db.find("u_akm_task",{"createTime": {"$gt": t}})
  File "../common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2020-04-21 14:38:24,573: Connect mongodb error! cause a error: 192.168.5.137:27017: timed out
pid=20796, ppid=19200, tid=1280

[CRITICAL]2020-04-21 14:38:24,581: update task error: cause a error: mongodb is not connected
pid=20796, ppid=19200, tid=1280
Traceback (most recent call last):
  File "E:/python_work/akm/akmCtrl/taskUI.py", line 150, in autoUpdateTask
    self.updateTaskBydb()
  File "E:/python_work/akm/akmCtrl/taskUI.py", line 128, in updateTaskBydb
    tasks = getAkmTask()
  File "E:/python_work/akm/akmCtrl/taskUI.py", line 160, in getAkmTask
    ds = db.find("u_akm_task",{"createTime": {"$gt": t}})
  File "../common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2020-04-21 14:39:24,567: Connect mongodb error! cause a error: 192.168.5.137:27017: timed out
pid=20796, ppid=19200, tid=1280

[CRITICAL]2020-04-21 14:39:24,575: update task error: cause a error: mongodb is not connected
pid=20796, ppid=19200, tid=1280
Traceback (most recent call last):
  File "E:/python_work/akm/akmCtrl/taskUI.py", line 150, in autoUpdateTask
    self.updateTaskBydb()
  File "E:/python_work/akm/akmCtrl/taskUI.py", line 128, in updateTaskBydb
    tasks = getAkmTask()
  File "E:/python_work/akm/akmCtrl/taskUI.py", line 160, in getAkmTask
    ds = db.find("u_akm_task",{"createTime": {"$gt": t}})
  File "../common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2020-04-21 14:40:24,585: Connect mongodb error! cause a error: 192.168.5.137:27017: timed out
pid=20796, ppid=19200, tid=1280

[CRITICAL]2020-04-21 14:40:24,594: update task error: cause a error: mongodb is not connected
pid=20796, ppid=19200, tid=1280
Traceback (most recent call last):
  File "E:/python_work/akm/akmCtrl/taskUI.py", line 150, in autoUpdateTask
    self.updateTaskBydb()
  File "E:/python_work/akm/akmCtrl/taskUI.py", line 128, in updateTaskBydb
    tasks = getAkmTask()
  File "E:/python_work/akm/akmCtrl/taskUI.py", line 160, in getAkmTask
    ds = db.find("u_akm_task",{"createTime": {"$gt": t}})
  File "../common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

[CRITICAL]2020-04-21 14:41:24,572: Connect mongodb error! cause a error: 192.168.5.137:27017: timed out
pid=20796, ppid=19200, tid=1280

[CRITICAL]2020-04-21 14:41:24,580: update task error: cause a error: mongodb is not connected
pid=20796, ppid=19200, tid=1280
Traceback (most recent call last):
  File "E:/python_work/akm/akmCtrl/taskUI.py", line 150, in autoUpdateTask
    self.updateTaskBydb()
  File "E:/python_work/akm/akmCtrl/taskUI.py", line 128, in updateTaskBydb
    tasks = getAkmTask()
  File "E:/python_work/akm/akmCtrl/taskUI.py", line 160, in getAkmTask
    ds = db.find("u_akm_task",{"createTime": {"$gt": t}})
  File "../common\mongodb.py", line 188, in find
    raise Exception("mongodb is not connected")
Exception: mongodb is not connected

