[CRITICAL]2021-06-15 10:01:47,761: invoke <function scadaTask._taskFunc at 0x00000191591E56A8> cause a error: 'NoneType' object is not subscriptable
pid=16628, ppid=13548, tid=14944
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\SVN\美维\MeiWei_back_0421\akmCtrl\beans\scadaTaskBean.py", line 836, in _taskFunc
    log.debug(str(self), old, "->", self.taskStep)
  File "C:\Users\Administrator\Desktop\SVN\美维\MeiWei_back_0421\akmCtrl\beans\scadaTaskBean.py", line 170, in __str__
    log.info(self.t_info["location"])
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "..\common\utility.py", line 167, in __call
    return func(*p,**pp)
  File "C:\Users\Administrator\Desktop\SVN\美维\MeiWei_back_0421\akmCtrl\beans\scadaTaskBean.py", line 842, in _taskFunc
    log.exception("taskFunc2:" + str(self), e)
  File "C:\Users\Administrator\Desktop\SVN\美维\MeiWei_back_0421\akmCtrl\beans\scadaTaskBean.py", line 170, in __str__
    log.info(self.t_info["location"])
TypeError: 'NoneType' object is not subscriptable

