[CRITICAL]2021-04-21 14:55:51,663: agvApi step callback cause a error: 'dict' object is not callable
pid=11904, ppid=11564, tid=12944
Traceback (most recent call last):
  File "..\agvCtrl\agvApi.py", line 263, in _checkFinish
    t.stepCallback(t.params,t.status)
TypeError: 'dict' object is not callable

[CRITICAL]2021-04-21 14:55:53,764: agvApi step callback cause a error: 'dict' object is not callable
pid=11904, ppid=11564, tid=12944
Traceback (most recent call last):
  File "..\agvCtrl\agvApi.py", line 263, in _checkFinish
    t.stepCallback(t.params,t.status)
TypeError: 'dict' object is not callable

[CRITICAL]2021-04-21 14:55:56,918: agvApi step callback cause a error: 'dict' object is not callable
pid=11904, ppid=11564, tid=12944
Traceback (most recent call last):
  File "..\agvCtrl\agvApi.py", line 263, in _checkFinish
    t.stepCallback(t.params,t.status)
TypeError: 'dict' object is not callable

[CRITICAL]2021-04-21 14:56:00,581: agvApi step callback cause a error: 'dict' object is not callable
pid=11904, ppid=11564, tid=12944
Traceback (most recent call last):
  File "..\agvCtrl\agvApi.py", line 263, in _checkFinish
    t.stepCallback(t.params,t.status)
TypeError: 'dict' object is not callable

[CRITICAL]2021-04-21 14:56:05,784: agvApi step callback cause a error: 'dict' object is not callable
pid=11904, ppid=11564, tid=12944
Traceback (most recent call last):
  File "..\agvCtrl\agvApi.py", line 263, in _checkFinish
    t.stepCallback(t.params,t.status)
TypeError: 'dict' object is not callable

[CRITICAL]2021-04-21 14:56:06,829: agvApi step callback cause a error: 'dict' object is not callable
pid=11904, ppid=11564, tid=12944
Traceback (most recent call last):
  File "..\agvCtrl\agvApi.py", line 263, in _checkFinish
    t.stepCallback(t.params,t.status)
TypeError: 'dict' object is not callable

[CRITICAL]2021-04-21 14:56:13,565: agvApi step callback cause a error: 'dict' object is not callable
pid=11904, ppid=11564, tid=12944
Traceback (most recent call last):
  File "..\agvCtrl\agvApi.py", line 263, in _checkFinish
    t.stepCallback(t.params,t.status)
TypeError: 'dict' object is not callable

