[INFO]2021-02-26 10:38:19,094: log files at D:\python_lx\akm\common\log
[INFO]2021-02-26 10:38:19,094: find module agvCtrl.main_agv
[INFO]2021-02-26 10:38:19,095: find module agvDevice.main_agvDevice
[INFO]2021-02-26 10:38:19,095: find module alarm.main_alarm
[INFO]2021-02-26 10:38:19,097: find module auth.main_auth
[INFO]2021-02-26 10:38:19,097: find module button.main_button
[INFO]2021-02-26 10:38:19,097: find module door.main_door
[INFO]2021-02-26 10:38:19,097: find module elevator.main_elevator
[INFO]2021-02-26 10:38:19,098: find module virtualDoor.main_doorCtrl
[INFO]2021-02-26 10:38:19,098: import agvCtrl.main_agv
[INFO]2021-02-26 10:38:19,565: create lock <lock name:doorMgr.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000029ABD7FC6C0>>
[INFO]2021-02-26 10:38:19,580: create lock <lock name:door.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000029ABD7FCF00>>
[INFO]2021-02-26 10:38:19,884: create lock <lock name:timer.lock_2863630870512,<unlocked _thread.RLock object owner=0 count=0 at 0x0000029ABDB36930>>
[ERROR]2021-02-26 10:38:19,912: mqtt is disabled
[INFO]2021-02-26 10:38:19,912: mqtt: subscribe [alarm/raise/+]
[INFO]2021-02-26 10:38:19,912: mqtt: subscribe [alarm/clear/+]
[INFO]2021-02-26 10:38:22,949: Mongodb connect to 127.0.0.1 port 27017
[INFO]2021-02-26 10:38:23,011: create lock <lock name:elevatorApi.tcp_lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000029ABDDC0D20>>
[INFO]2021-02-26 10:38:23,012: create lock <lock name:elevatorApi.g_lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000029ABDDC0660>>
[INFO]2021-02-26 10:38:23,014: create lock <lock name:elevatorMgr.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000029ABDDB4A80>>
[INFO]2021-02-26 10:38:23,049: create lock <lock name:agvserver,<unlocked _thread.RLock object owner=0 count=0 at 0x0000029ABDE01E40>>
[INFO]2021-02-26 10:38:24,077: create lock <lock name:mapMgr.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000029ABDDC7B40>>
[INFO]2021-02-26 10:38:24,390: create lock <lock name:agvList.g_agvLock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000029ABDEAC840>>
[INFO]2021-02-26 10:38:24,393: create lock <lock name:taskList.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000029ABDF61210>>
[INFO]2021-02-26 10:38:24,524: charge policy 0 , fix time
[INFO]2021-02-26 10:38:24,630: create lock <lock name:agvApi.g_lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000029ABDF61DE0>>
[INFO]2021-02-26 10:38:25,582: start load map D:\python_lx\akm\agvCtrl\projects\akm\AKM-AOI.smap
[DEBUG]2021-02-26 10:38:25,994: elevator thread start
[INFO]2021-02-26 10:38:26,013: load map D:\python_lx\akm\agvCtrl\projects\akm\AKM-AOI.smap ,used 439 ms
[INFO]2021-02-26 10:38:26,025: start load map D:\python_lx\akm\agvCtrl\projects\akm\AKM-DC.smap
[INFO]2021-02-26 10:38:26,107: load map D:\python_lx\akm\agvCtrl\projects\akm\AKM-DC.smap ,used 93 ms
[INFO]2021-02-26 10:38:26,129: start load map D:\python_lx\akm\agvCtrl\projects\akm\AKM-DDT.smap
[INFO]2021-02-26 10:38:26,354: load map D:\python_lx\akm\agvCtrl\projects\akm\AKM-DDT.smap ,used 247 ms
[INFO]2021-02-26 10:38:26,385: start load map D:\python_lx\akm\agvCtrl\projects\akm\AKM-FQC.smap
[INFO]2021-02-26 10:38:26,605: load map D:\python_lx\akm\agvCtrl\projects\akm\AKM-FQC.smap ,used 251 ms
[INFO]2021-02-26 10:38:26,616: start load map D:\python_lx\akm\agvCtrl\projects\akm\AKM-LYH.smap
[INFO]2021-02-26 10:38:26,737: load map D:\python_lx\akm\agvCtrl\projects\akm\AKM-LYH.smap ,used 132 ms
[INFO]2021-02-26 10:38:26,758: start load map D:\python_lx\akm\agvCtrl\projects\akm\AKM-ZP.smap
[INFO]2021-02-26 10:38:26,996: load map D:\python_lx\akm\agvCtrl\projects\akm\AKM-ZP.smap ,used 259 ms
[INFO]2021-02-26 10:38:27,021: start load map D:\python_lx\akm\agvCtrl\projects\akm\office.smap
[INFO]2021-02-26 10:38:27,109: load map D:\python_lx\akm\agvCtrl\projects\akm\office.smap ,used 113 ms
[INFO]2021-02-26 10:38:27,118: import agvDevice.main_agvDevice
[INFO]2021-02-26 10:38:27,118: import alarm.main_alarm
[INFO]2021-02-26 10:38:27,118: import auth.main_auth
[INFO]2021-02-26 10:38:27,146: import button.main_button
[INFO]2021-02-26 10:38:27,158: create lock <lock name:agvApi.g_lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000029ABE479AB0>>
[INFO]2021-02-26 10:38:27,277: import door.main_door
[INFO]2021-02-26 10:38:27,284: import elevator.main_elevator
[INFO]2021-02-26 10:38:27,285: import virtualDoor.main_doorCtrl
[CRITICAL]2021-02-26 10:38:30,782: import main_doorCtrl failed, path: virtualDoor cause a error: No module named 'runTasks'
pid=3236, ppid=19028, tid=10116
Traceback (most recent call last):
  File "D:/python_lx/akm/common/run_all.py", line 40, in findModule
    __import__(m[1])
  File "D:\python_lx\akm\virtualDoor\main_doorCtrl.py", line 18, in <module>
    import doorCtrlRunTasks
  File "D:\python_lx\akm\virtualDoor\doorCtrlRunTasks.py", line 20, in <module>
    import magneticAGV
  File "D:\python_lx\akm\virtualDoor\magneticAGV.py", line 24, in <module>
    import runTasks
ModuleNotFoundError: No module named 'runTasks'

[CRITICAL]2021-02-26 10:38:30,783: import main_doorCtrl failed, path: virtualDoor ,cause No module named 'runTasks'
[INFO]2021-02-26 10:38:31,548: load agv file: D:\python_lx\akm\agvCtrl/projects/akm/agv.cfg
[INFO]2021-02-26 10:38:31,548: create lock <lock name:agvList.AGV23.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x0000029ABBDBCCF0>>
[DEBUG]2021-02-26 10:38:31,554: create aliveObj AGV23 AGV¿Îœﬂ“Ï≥£ timeout 300
[INFO]2021-02-26 10:38:31,555: AGV23 start agvList run thread
[INFO]2021-02-26 10:38:31,556: create lock <lock name:agv.AGV23.lock_status,<unlocked _thread.RLock object owner=0 count=0 at 0x0000029ABE4CE510>>
[DEBUG]2021-02-26 10:38:31,556: try connect AGV23 192.168.20.198:19204
[INFO]2021-02-26 10:38:31,557: AGV23 start agvList run2 thread
[ERROR]2021-02-26 10:38:41,558: connect AGV23 failed timed out
[DEBUG]2021-02-26 10:38:41,560: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:38:51,562: connect AGV23 failed timed out
[INFO]2021-02-26 10:38:51,563: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:38:51,564: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 20008 ms
[INFO]2021-02-26 10:38:51,567: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:38:53,569: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:39:03,571: connect AGV23 failed timed out
[INFO]2021-02-26 10:39:03,571: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:39:03,572: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10003 ms
[INFO]2021-02-26 10:39:03,574: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:39:05,576: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:39:15,578: connect AGV23 failed timed out
[INFO]2021-02-26 10:39:15,578: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:39:15,578: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10002 ms
[INFO]2021-02-26 10:39:15,579: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:39:17,580: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:39:27,581: connect AGV23 failed timed out
[INFO]2021-02-26 10:39:27,582: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:39:27,582: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10002 ms
[INFO]2021-02-26 10:39:27,585: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:39:29,585: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:39:39,587: connect AGV23 failed timed out
[INFO]2021-02-26 10:39:39,588: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:39:39,589: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10004 ms
[INFO]2021-02-26 10:39:39,593: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:39:41,595: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:39:51,596: connect AGV23 failed timed out
[INFO]2021-02-26 10:39:51,597: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:39:51,598: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10003 ms
[INFO]2021-02-26 10:39:51,600: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:39:53,602: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:40:03,604: connect AGV23 failed timed out
[INFO]2021-02-26 10:40:03,604: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:40:03,605: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10003 ms
[INFO]2021-02-26 10:40:03,608: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:40:05,609: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:40:15,612: connect AGV23 failed timed out
[INFO]2021-02-26 10:40:15,613: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:40:15,613: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10004 ms
[INFO]2021-02-26 10:40:15,615: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:40:17,618: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:40:27,620: connect AGV23 failed timed out
[INFO]2021-02-26 10:40:27,621: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:40:27,622: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10004 ms
[INFO]2021-02-26 10:40:27,626: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:40:29,628: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:40:39,631: connect AGV23 failed timed out
[INFO]2021-02-26 10:40:39,632: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:40:39,632: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10004 ms
[INFO]2021-02-26 10:40:39,634: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:40:41,636: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:40:51,639: connect AGV23 failed timed out
[INFO]2021-02-26 10:40:51,640: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:40:51,641: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10004 ms
[INFO]2021-02-26 10:40:51,643: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:40:53,644: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:41:03,647: connect AGV23 failed timed out
[INFO]2021-02-26 10:41:03,648: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:41:03,648: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10004 ms
[INFO]2021-02-26 10:41:03,650: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:41:05,652: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:41:15,653: connect AGV23 failed timed out
[INFO]2021-02-26 10:41:15,654: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:41:15,655: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10003 ms
[INFO]2021-02-26 10:41:15,657: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:41:17,659: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:41:27,661: connect AGV23 failed timed out
[INFO]2021-02-26 10:41:27,662: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:41:27,663: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10004 ms
[INFO]2021-02-26 10:41:27,666: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:41:29,667: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:41:39,669: connect AGV23 failed timed out
[INFO]2021-02-26 10:41:39,670: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:41:39,671: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10004 ms
[INFO]2021-02-26 10:41:39,674: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:41:41,676: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:41:51,678: connect AGV23 failed timed out
[INFO]2021-02-26 10:41:51,679: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:41:51,680: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10004 ms
[INFO]2021-02-26 10:41:51,684: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:41:53,717: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:42:03,788: connect AGV23 failed timed out
[INFO]2021-02-26 10:42:03,788: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:42:03,789: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10072 ms
[INFO]2021-02-26 10:42:03,791: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:42:05,793: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:42:15,795: connect AGV23 failed timed out
[INFO]2021-02-26 10:42:15,795: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:42:15,797: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10004 ms
[INFO]2021-02-26 10:42:15,799: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:42:17,800: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:42:27,802: connect AGV23 failed timed out
[INFO]2021-02-26 10:42:27,803: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:42:27,804: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10004 ms
[INFO]2021-02-26 10:42:27,806: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:42:29,807: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:42:39,808: connect AGV23 failed timed out
[INFO]2021-02-26 10:42:39,808: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:42:39,809: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10002 ms
[INFO]2021-02-26 10:42:39,810: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:42:41,812: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:42:51,814: connect AGV23 failed timed out
[INFO]2021-02-26 10:42:51,815: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:42:51,815: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10003 ms
[INFO]2021-02-26 10:42:51,817: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:42:53,819: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:43:03,821: connect AGV23 failed timed out
[INFO]2021-02-26 10:43:03,822: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:43:03,823: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10004 ms
[INFO]2021-02-26 10:43:03,824: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:43:05,827: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:43:15,829: connect AGV23 failed timed out
[INFO]2021-02-26 10:43:15,830: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:43:15,831: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10004 ms
[INFO]2021-02-26 10:43:15,833: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:43:17,835: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:43:27,837: connect AGV23 failed timed out
[INFO]2021-02-26 10:43:27,837: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:43:27,839: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10004 ms
[INFO]2021-02-26 10:43:27,839: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:43:29,841: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:43:39,842: connect AGV23 failed timed out
[INFO]2021-02-26 10:43:39,843: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:43:39,843: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10002 ms
[INFO]2021-02-26 10:43:39,844: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:43:41,847: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:43:51,848: connect AGV23 failed timed out
[INFO]2021-02-26 10:43:51,849: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:43:51,850: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10003 ms
[INFO]2021-02-26 10:43:51,852: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:43:53,855: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:44:03,857: connect AGV23 failed timed out
[INFO]2021-02-26 10:44:03,857: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:44:03,858: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10003 ms
[INFO]2021-02-26 10:44:03,862: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:44:05,863: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:44:15,865: connect AGV23 failed timed out
[INFO]2021-02-26 10:44:15,867: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:44:15,868: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10004 ms
[INFO]2021-02-26 10:44:15,871: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:44:17,873: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:44:27,875: connect AGV23 failed timed out
[INFO]2021-02-26 10:44:27,876: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:44:27,877: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10003 ms
[INFO]2021-02-26 10:44:27,879: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:44:29,882: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:44:39,883: connect AGV23 failed timed out
[INFO]2021-02-26 10:44:39,885: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:44:39,885: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10003 ms
[INFO]2021-02-26 10:44:39,888: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:44:41,891: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:44:51,893: connect AGV23 failed timed out
[INFO]2021-02-26 10:44:51,894: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:44:51,895: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10004 ms
[INFO]2021-02-26 10:44:51,897: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:44:53,898: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:45:03,901: connect AGV23 failed timed out
[INFO]2021-02-26 10:45:03,902: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:45:03,903: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10005 ms
[INFO]2021-02-26 10:45:03,905: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:45:05,907: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:45:15,910: connect AGV23 failed timed out
[INFO]2021-02-26 10:45:15,911: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:45:15,911: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10004 ms
[INFO]2021-02-26 10:45:15,913: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:45:17,915: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:45:27,916: connect AGV23 failed timed out
[INFO]2021-02-26 10:45:27,917: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:45:27,917: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10002 ms
[INFO]2021-02-26 10:45:27,920: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:45:29,922: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:45:39,923: connect AGV23 failed timed out
[INFO]2021-02-26 10:45:39,924: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:45:39,925: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10003 ms
[INFO]2021-02-26 10:45:39,928: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:45:41,929: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:45:51,932: connect AGV23 failed timed out
[INFO]2021-02-26 10:45:51,933: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:45:51,934: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10005 ms
[INFO]2021-02-26 10:45:51,936: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:45:53,937: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:46:03,939: connect AGV23 failed timed out
[INFO]2021-02-26 10:46:03,940: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:46:03,941: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10003 ms
[INFO]2021-02-26 10:46:03,943: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:46:05,945: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:46:15,948: connect AGV23 failed timed out
[INFO]2021-02-26 10:46:15,948: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:46:15,949: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10004 ms
[INFO]2021-02-26 10:46:15,951: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:46:17,952: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:46:27,955: connect AGV23 failed timed out
[INFO]2021-02-26 10:46:27,956: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:46:27,956: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10004 ms
[INFO]2021-02-26 10:46:27,958: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:46:29,960: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:46:39,962: connect AGV23 failed timed out
[INFO]2021-02-26 10:46:39,962: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:46:39,963: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10003 ms
[INFO]2021-02-26 10:46:39,965: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:46:41,968: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:46:51,969: connect AGV23 failed timed out
[INFO]2021-02-26 10:46:51,970: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:46:51,970: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10002 ms
[INFO]2021-02-26 10:46:51,973: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:46:53,974: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:47:03,975: connect AGV23 failed timed out
[INFO]2021-02-26 10:47:03,976: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:47:03,977: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10002 ms
[INFO]2021-02-26 10:47:03,979: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:47:05,981: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:47:15,983: connect AGV23 failed timed out
[INFO]2021-02-26 10:47:15,984: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:47:15,985: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10004 ms
[INFO]2021-02-26 10:47:15,987: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:47:17,989: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:47:27,990: connect AGV23 failed timed out
[INFO]2021-02-26 10:47:27,991: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:47:27,992: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10003 ms
[INFO]2021-02-26 10:47:27,994: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:47:29,997: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:47:39,999: connect AGV23 failed timed out
[INFO]2021-02-26 10:47:40,000: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:47:40,001: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10004 ms
[INFO]2021-02-26 10:47:40,004: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:47:42,006: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:47:52,009: connect AGV23 failed timed out
[INFO]2021-02-26 10:47:52,010: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:47:52,011: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10005 ms
[INFO]2021-02-26 10:47:52,014: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:47:54,015: try connect AGV23 192.168.20.198:19204
[ERROR]2021-02-26 10:48:04,017: connect AGV23 failed timed out
[INFO]2021-02-26 10:48:04,018: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-02-26 10:48:04,019: agvThread.AGV23[tid:14140] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=14140 count=1 at 0x0000029ABE4CE510>> ,hold 10003 ms
[INFO]2021-02-26 10:48:04,021: name=agvThread.AGV23, pid=3236, tid=14140
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-02-26 10:48:06,022: try connect AGV23 192.168.20.198:19204
