[INFO]2021-03-03 15:57:42,090: log files at D:\python_lx\akm\common\log
[INFO]2021-03-03 15:57:42,091: find module agvCtrl.main_agv
[INFO]2021-03-03 15:57:42,091: find module agvDevice.main_agvDevice
[INFO]2021-03-03 15:57:42,091: find module alarm.main_alarm
[INFO]2021-03-03 15:57:42,091: find module auth.main_auth
[INFO]2021-03-03 15:57:42,092: find module button.main_button
[INFO]2021-03-03 15:57:42,092: find module door.main_door
[INFO]2021-03-03 15:57:42,092: find module elevator.main_elevator
[INFO]2021-03-03 15:57:42,092: find module virtualDoor.main_doorCtrl
[INFO]2021-03-03 15:57:42,092: import agvCtrl.main_agv
[INFO]2021-03-03 15:57:42,489: create lock <lock name:doorMgr.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x000001B3E2A1D630>>
[INFO]2021-03-03 15:57:42,494: create lock <lock name:door.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x000001B3E2A2D810>>
[INFO]2021-03-03 15:57:42,495: create lock <lock name:door.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x000001B3E2A2DA20>>
[INFO]2021-03-03 15:57:42,572: create lock <lock name:timer.lock_1872116268816,<unlocked _thread.RLock object owner=0 count=0 at 0x000001B3E2D43090>>
[ERROR]2021-03-03 15:57:42,581: mqtt is disabled
[INFO]2021-03-03 15:57:42,582: mqtt: subscribe [alarm/raise/+]
[INFO]2021-03-03 15:57:42,582: mqtt: subscribe [alarm/clear/+]
[INFO]2021-03-03 15:57:45,608: Mongodb connect to 127.0.0.1 port 27017
[INFO]2021-03-03 15:57:45,631: create lock <lock name:elevatorApi.tcp_lock,<unlocked _thread.RLock object owner=0 count=0 at 0x000001B3E2FC7480>>
[INFO]2021-03-03 15:57:45,631: create lock <lock name:elevatorApi.g_lock,<unlocked _thread.RLock object owner=0 count=0 at 0x000001B3E2FBFD80>>
[INFO]2021-03-03 15:57:45,631: create lock <lock name:elevatorMgr.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x000001B3E2FBF1E0>>
[INFO]2021-03-03 15:57:45,639: create lock <lock name:agvserver,<unlocked _thread.RLock object owner=0 count=0 at 0x000001B3E300B5A0>>
[INFO]2021-03-03 15:57:45,907: create lock <lock name:mapMgr.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x000001B3E2FD12A0>>
[INFO]2021-03-03 15:57:46,175: create lock <lock name:agvList.g_agvLock,<unlocked _thread.RLock object owner=0 count=0 at 0x000001B3E30A6FC0>>
[INFO]2021-03-03 15:57:46,180: create lock <lock name:taskList.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x000001B3E3160930>>
[INFO]2021-03-03 15:57:46,259: charge policy 0 , fix time
[INFO]2021-03-03 15:57:46,287: create lock <lock name:agvApi.g_lock,<unlocked _thread.RLock object owner=0 count=0 at 0x000001B3E316C540>>
[INFO]2021-03-03 15:57:46,689: start load map D:\python_lx\akm\agvCtrl\projects\akm\AKM-AOI.smap
[DEBUG]2021-03-03 15:57:46,873: elevator thread start
[INFO]2021-03-03 15:57:46,890: load map D:\python_lx\akm\agvCtrl\projects\akm\AKM-AOI.smap ,used 210 ms
[INFO]2021-03-03 15:57:46,898: start load map D:\python_lx\akm\agvCtrl\projects\akm\AKM-DC.smap
[INFO]2021-03-03 15:57:46,953: load map D:\python_lx\akm\agvCtrl\projects\akm\AKM-DC.smap ,used 63 ms
[INFO]2021-03-03 15:57:46,961: start load map D:\python_lx\akm\agvCtrl\projects\akm\AKM-DDT.smap
[INFO]2021-03-03 15:57:47,048: load map D:\python_lx\akm\agvCtrl\projects\akm\AKM-DDT.smap ,used 95 ms
[INFO]2021-03-03 15:57:47,056: start load map D:\python_lx\akm\agvCtrl\projects\akm\AKM-FQC.smap
[DEBUG]2021-03-03 15:57:47,213: create aliveObj SK_DOOR 门控离线异常 timeout 60
[DEBUG]2021-03-03 15:57:47,213: create aliveObj vitualDoor01 门控离线异常 timeout 60
[DEBUG]2021-03-03 15:57:47,213: create aliveObj vitualDoor02 门控离线异常 timeout 60
[INFO]2021-03-03 15:57:47,233: load map D:\python_lx\akm\agvCtrl\projects\akm\AKM-FQC.smap ,used 184 ms
[INFO]2021-03-03 15:57:47,241: start load map D:\python_lx\akm\agvCtrl\projects\akm\AKM-LYH.smap
[INFO]2021-03-03 15:57:47,335: load map D:\python_lx\akm\agvCtrl\projects\akm\AKM-LYH.smap ,used 102 ms
[INFO]2021-03-03 15:57:47,344: start load map D:\python_lx\akm\agvCtrl\projects\akm\AKM-ZP.smap
[INFO]2021-03-03 15:57:47,419: load map D:\python_lx\akm\agvCtrl\projects\akm\AKM-ZP.smap ,used 84 ms
[INFO]2021-03-03 15:57:47,430: start load map D:\python_lx\akm\agvCtrl\projects\akm\office.smap
[INFO]2021-03-03 15:57:47,474: load map D:\python_lx\akm\agvCtrl\projects\akm\office.smap ,used 54 ms
[INFO]2021-03-03 15:57:47,477: import agvDevice.main_agvDevice
[INFO]2021-03-03 15:57:47,477: import alarm.main_alarm
[INFO]2021-03-03 15:57:47,478: import auth.main_auth
[INFO]2021-03-03 15:57:47,485: import button.main_button
[INFO]2021-03-03 15:57:47,489: create lock <lock name:agvApi.g_lock,<unlocked _thread.RLock object owner=0 count=0 at 0x000001B3E3680C60>>
[INFO]2021-03-03 15:57:47,517: import door.main_door
[INFO]2021-03-03 15:57:47,519: import elevator.main_elevator
[INFO]2021-03-03 15:57:47,520: import virtualDoor.main_doorCtrl
[INFO]2021-03-03 15:57:49,123: create lock <lock name:IOAlarm.s_lock,<unlocked _thread.RLock object owner=0 count=0 at 0x000001B3E37D3960>>
[DEBUG]2021-03-03 15:57:49,125: create aliveObj magneticAGV01 二维码掉线异常 timeout 120
[SUCC]2021-03-03 15:57:49,133: utility start, pid=8432, ppid=432
[DEBUG]2021-03-03 15:57:49,136: start timer
[INFO]2021-03-03 15:57:49,143: load agv file: D:\python_lx\akm\agvCtrl/projects/akm/agv.cfg
[INFO]2021-03-03 15:57:49,143: create lock <lock name:agvList.AGV23.lock,<unlocked _thread.RLock object owner=0 count=0 at 0x000001B3EB1DEEA0>>
[DEBUG]2021-03-03 15:57:49,145: create aliveObj AGV23 AGV离线异常 timeout 300
[INFO]2021-03-03 15:57:49,145: AGV23 start agvList run thread
[INFO]2021-03-03 15:57:49,145: create lock <lock name:agv.AGV23.lock_status,<unlocked _thread.RLock object owner=0 count=0 at 0x000001B3EB1F8630>>
[DEBUG]2021-03-03 15:57:49,146: try connect AGV23 192.168.20.198:19204
[INFO]2021-03-03 15:57:49,146: AGV23 start agvList run2 thread
[WARN]2021-03-03 15:57:49,148: Local server start! version 3.8.0, path D:\python_lx\akm\common, pid 8432
[INFO]2021-03-03 15:57:49,148: add_ignore: taskStatus
[INFO]2021-03-03 15:57:53,190: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 15:57:56,199: magneticAGV01 (0, 0, 0, 0)
[ERROR]2021-03-03 15:57:59,146: connect AGV23 failed timed out
[DEBUG]2021-03-03 15:57:59,146: try connect AGV23 192.168.20.198:19204
[INFO]2021-03-03 15:57:59,210: startCharge is false
[INFO]2021-03-03 15:57:59,214: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 15:58:02,233: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 15:58:05,249: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 15:58:08,264: magneticAGV01 (0, 0, 0, 0)
[ERROR]2021-03-03 15:58:09,147: connect AGV23 failed timed out
[INFO]2021-03-03 15:58:09,148: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-03-03 15:58:09,148: agvThread.AGV23[tid:18324] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=18324 count=1 at 0x000001B3EB1F8630>> ,hold 20002 ms
[INFO]2021-03-03 15:58:09,151: name=agvThread.AGV23, pid=8432, tid=18324
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-03-03 15:58:11,152: try connect AGV23 192.168.20.198:19204
[INFO]2021-03-03 15:58:11,268: startCharge is false
[INFO]2021-03-03 15:58:11,273: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 15:58:14,287: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 15:58:17,302: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 15:58:20,311: magneticAGV01 (0, 0, 0, 0)
[ERROR]2021-03-03 15:58:21,154: connect AGV23 failed timed out
[INFO]2021-03-03 15:58:21,156: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-03-03 15:58:21,157: agvThread.AGV23[tid:18324] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=18324 count=1 at 0x000001B3EB1F8630>> ,hold 10005 ms
[INFO]2021-03-03 15:58:21,161: name=agvThread.AGV23, pid=8432, tid=18324
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-03-03 15:58:23,163: try connect AGV23 192.168.20.198:19204
[INFO]2021-03-03 15:58:23,313: startCharge is false
[INFO]2021-03-03 15:58:23,318: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 15:58:26,327: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 15:58:29,337: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 15:58:32,352: magneticAGV01 (0, 0, 0, 0)
[ERROR]2021-03-03 15:58:33,165: connect AGV23 failed timed out
[INFO]2021-03-03 15:58:33,165: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-03-03 15:58:33,165: agvThread.AGV23[tid:18324] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=18324 count=1 at 0x000001B3EB1F8630>> ,hold 10002 ms
[INFO]2021-03-03 15:58:33,166: name=agvThread.AGV23, pid=8432, tid=18324
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-03-03 15:58:35,166: try connect AGV23 192.168.20.198:19204
[INFO]2021-03-03 15:58:35,355: startCharge is false
[INFO]2021-03-03 15:58:35,360: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 15:58:38,370: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 15:58:41,387: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 15:58:44,402: magneticAGV01 (0, 0, 0, 0)
[ERROR]2021-03-03 15:58:45,168: connect AGV23 failed timed out
[INFO]2021-03-03 15:58:45,169: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-03-03 15:58:45,170: agvThread.AGV23[tid:18324] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=18324 count=1 at 0x000001B3EB1F8630>> ,hold 10004 ms
[INFO]2021-03-03 15:58:45,173: name=agvThread.AGV23, pid=8432, tid=18324
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-03-03 15:58:47,174: try connect AGV23 192.168.20.198:19204
[INFO]2021-03-03 15:58:47,406: startCharge is false
[INFO]2021-03-03 15:58:47,411: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 15:58:50,423: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 15:58:53,430: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 15:58:56,440: magneticAGV01 (0, 0, 0, 0)
[ERROR]2021-03-03 15:58:57,176: connect AGV23 failed timed out
[INFO]2021-03-03 15:58:57,176: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-03-03 15:58:57,177: agvThread.AGV23[tid:18324] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=18324 count=1 at 0x000001B3EB1F8630>> ,hold 10003 ms
[INFO]2021-03-03 15:58:57,178: name=agvThread.AGV23, pid=8432, tid=18324
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[DEBUG]2021-03-03 15:58:59,180: try connect AGV23 192.168.20.198:19204
[INFO]2021-03-03 15:58:59,443: startCharge is false
[INFO]2021-03-03 15:58:59,448: magneticAGV01 (1, 0, 0, 0)
[INFO]2021-03-03 15:59:00,450: magneticAGV01 try to open door 0 ['SK_DOOR'] ['SK_DOOR']
[INFO]2021-03-03 15:59:00,457: task [magneticAGV01] readIo get status  (1, 0, 0, 0, 0, 0, 0, 0)
[DEBUG]2021-03-03 15:59:00,458: magneticAGV01 经过门 ['SK_DOOR'] checkBeginSignal -> opendoor
[INFO]2021-03-03 15:59:00,959: try to open door SK_DOOR
[DEBUG]2021-03-03 15:59:00,960: send http_get: http://127.0.0.1:8999/api/switch/on?id=SK_DOOR
[DEBUG]2021-03-03 15:59:00,981: GET: http://127.0.0.1:8999/api/switch/on?id=SK_DOOR addr: 127.0.0.1
[INFO]2021-03-03 15:59:00,983: The signal to open the door has been sent,  doorIP:192.168.252.253
[DEBUG]2021-03-03 15:59:01,003: send to door module:192.168.252.253, values:outbuf[16] 55 00 00 00 00 AA 03 06 80 00 00 00 00 00 88 16
[DEBUG]2021-03-03 15:59:01,305: read from door module:192.168.252.253, values:inbuf[13] 55 00 00 00 00 AA 83 03 80 01 00 06 16
[DEBUG]2021-03-03 15:59:01,307: used 326ms 200 OK application/json;charset=utf-8, GET: http://127.0.0.1:8999/api/switch/on?id=SK_DOOR
[DEBUG]2021-03-03 15:59:01,311: [return] use 351 ms,http_get: http://127.0.0.1:8999/api/switch/on?id=SK_DOOR
[WARN]2021-03-03 15:59:01,312: magneticAGV01 经过门 ['SK_DOOR'] opendoor error
[INFO]2021-03-03 15:59:02,466: magneticAGV01 (0, 0, 0, 0)
[DEBUG]2021-03-03 15:59:03,314: magneticAGV01 经过门 ['SK_DOOR'] opendoor -> leavefirst
[INFO]2021-03-03 15:59:04,878: task: [magneticAGV01] readDo status  (1, 0, 0, 0, 0, 0, 0, 0)
[DEBUG]2021-03-03 15:59:04,879: magneticAGV01 经过门 ['SK_DOOR'] leavefirst -> waitAlway
[INFO]2021-03-03 15:59:05,384: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 15:59:05,385: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 15:59:05,475: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 15:59:07,390: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 15:59:07,391: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 15:59:08,486: magneticAGV01 (0, 0, 0, 0)
[ERROR]2021-03-03 15:59:09,183: connect AGV23 failed timed out
[INFO]2021-03-03 15:59:09,183: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-03-03 15:59:09,183: agvThread.AGV23[tid:18324] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=18324 count=1 at 0x000001B3EB1F8630>> ,hold 10003 ms
[INFO]2021-03-03 15:59:09,184: name=agvThread.AGV23, pid=8432, tid=18324
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[INFO]2021-03-03 15:59:09,396: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 15:59:09,396: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[DEBUG]2021-03-03 15:59:11,185: try connect AGV23 192.168.20.198:19204
[INFO]2021-03-03 15:59:11,402: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 15:59:11,403: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 15:59:11,488: startCharge is false
[INFO]2021-03-03 15:59:11,493: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 15:59:13,408: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 15:59:13,409: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 15:59:14,503: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 15:59:15,420: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 15:59:15,420: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 15:59:17,425: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 15:59:17,425: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 15:59:17,520: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 15:59:19,431: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 15:59:19,432: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 15:59:20,530: magneticAGV01 (0, 0, 0, 0)
[ERROR]2021-03-03 15:59:21,186: connect AGV23 failed timed out
[INFO]2021-03-03 15:59:21,187: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-03-03 15:59:21,188: agvThread.AGV23[tid:18324] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=18324 count=1 at 0x000001B3EB1F8630>> ,hold 10003 ms
[INFO]2021-03-03 15:59:21,190: name=agvThread.AGV23, pid=8432, tid=18324
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[INFO]2021-03-03 15:59:21,437: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 15:59:21,438: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[DEBUG]2021-03-03 15:59:23,192: try connect AGV23 192.168.20.198:19204
[INFO]2021-03-03 15:59:23,442: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 15:59:23,443: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 15:59:23,535: startCharge is false
[INFO]2021-03-03 15:59:23,539: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 15:59:25,448: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 15:59:25,449: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 15:59:26,555: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 15:59:27,455: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 15:59:27,455: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 15:59:29,460: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 15:59:29,461: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 15:59:29,572: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 15:59:31,465: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 15:59:31,465: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 15:59:32,584: magneticAGV01 (0, 0, 0, 0)
[ERROR]2021-03-03 15:59:33,195: connect AGV23 failed timed out
[INFO]2021-03-03 15:59:33,196: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-03-03 15:59:33,197: agvThread.AGV23[tid:18324] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=18324 count=1 at 0x000001B3EB1F8630>> ,hold 10005 ms
[INFO]2021-03-03 15:59:33,200: name=agvThread.AGV23, pid=8432, tid=18324
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[INFO]2021-03-03 15:59:33,471: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 1, 0)
[WARN]2021-03-03 15:59:33,471: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[DEBUG]2021-03-03 15:59:35,202: try connect AGV23 192.168.20.198:19204
[INFO]2021-03-03 15:59:35,476: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 1, 0)
[WARN]2021-03-03 15:59:35,477: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 15:59:35,587: startCharge is false
[INFO]2021-03-03 15:59:35,592: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 15:59:37,483: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 15:59:37,484: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 15:59:38,608: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 15:59:39,491: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 15:59:39,492: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 15:59:41,497: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 15:59:41,498: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 15:59:41,623: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 15:59:43,503: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 15:59:43,503: magneticAGV01 经过门 ['SK_DOOR'] waitAlway error
[INFO]2021-03-03 15:59:44,639: magneticAGV01 (0, 0, 0, 0)
[ERROR]2021-03-03 15:59:45,205: connect AGV23 failed timed out
[INFO]2021-03-03 15:59:45,205: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-03-03 15:59:45,206: agvThread.AGV23[tid:18324] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=18324 count=1 at 0x000001B3EB1F8630>> ,hold 10004 ms
[INFO]2021-03-03 15:59:45,207: name=agvThread.AGV23, pid=8432, tid=18324
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[INFO]2021-03-03 15:59:45,507: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 1)
[DEBUG]2021-03-03 15:59:45,507: magneticAGV01 经过门 ['SK_DOOR'] waitAlway -> clearfirst
[INFO]2021-03-03 15:59:47,099: task: [magneticAGV01] readDo status  (0, 0, 0, 0, 0, 0, 0, 0)
[DEBUG]2021-03-03 15:59:47,100: magneticAGV01 经过门 ['SK_DOOR'] clearfirst -> checkfinishSignal
[DEBUG]2021-03-03 15:59:47,209: try connect AGV23 192.168.20.198:19204
[INFO]2021-03-03 15:59:47,606: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 15:59:47,606: magneticAGV01 经过门 ['SK_DOOR'] checkfinishSignal error
[INFO]2021-03-03 15:59:47,642: startCharge is false
[INFO]2021-03-03 15:59:47,647: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 15:59:49,613: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 15:59:49,614: magneticAGV01 经过门 ['SK_DOOR'] checkfinishSignal error
[INFO]2021-03-03 15:59:50,655: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 15:59:51,620: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 15:59:51,621: magneticAGV01 经过门 ['SK_DOOR'] checkfinishSignal error
[INFO]2021-03-03 15:59:53,627: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 15:59:53,628: magneticAGV01 经过门 ['SK_DOOR'] checkfinishSignal error
[INFO]2021-03-03 15:59:53,671: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 15:59:55,632: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 15:59:55,632: magneticAGV01 经过门 ['SK_DOOR'] checkfinishSignal error
[INFO]2021-03-03 15:59:56,688: magneticAGV01 (0, 0, 0, 0)
[ERROR]2021-03-03 15:59:57,211: connect AGV23 failed timed out
[INFO]2021-03-03 15:59:57,212: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-03-03 15:59:57,213: agvThread.AGV23[tid:18324] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=18324 count=1 at 0x000001B3EB1F8630>> ,hold 10004 ms
[INFO]2021-03-03 15:59:57,215: name=agvThread.AGV23, pid=8432, tid=18324
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[INFO]2021-03-03 15:59:57,637: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 15:59:57,638: magneticAGV01 经过门 ['SK_DOOR'] checkfinishSignal error
[DEBUG]2021-03-03 15:59:59,216: try connect AGV23 192.168.20.198:19204
[INFO]2021-03-03 15:59:59,643: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 15:59:59,644: magneticAGV01 经过门 ['SK_DOOR'] checkfinishSignal error
[INFO]2021-03-03 15:59:59,691: startCharge is false
[INFO]2021-03-03 15:59:59,695: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 16:00:01,649: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 16:00:01,650: magneticAGV01 经过门 ['SK_DOOR'] checkfinishSignal error
[INFO]2021-03-03 16:00:02,710: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 16:00:03,654: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 16:00:03,655: magneticAGV01 经过门 ['SK_DOOR'] checkfinishSignal error
[INFO]2021-03-03 16:00:05,668: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 16:00:05,669: magneticAGV01 经过门 ['SK_DOOR'] checkfinishSignal error
[INFO]2021-03-03 16:00:05,718: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 16:00:07,676: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 16:00:07,677: magneticAGV01 经过门 ['SK_DOOR'] checkfinishSignal error
[INFO]2021-03-03 16:00:08,727: magneticAGV01 (0, 0, 0, 0)
[ERROR]2021-03-03 16:00:09,218: connect AGV23 failed timed out
[INFO]2021-03-03 16:00:09,219: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-03-03 16:00:09,220: agvThread.AGV23[tid:18324] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=18324 count=1 at 0x000001B3EB1F8630>> ,hold 10004 ms
[INFO]2021-03-03 16:00:09,222: name=agvThread.AGV23, pid=8432, tid=18324
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[INFO]2021-03-03 16:00:09,682: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 16:00:09,682: magneticAGV01 经过门 ['SK_DOOR'] checkfinishSignal error
[DEBUG]2021-03-03 16:00:11,224: try connect AGV23 192.168.20.198:19204
[INFO]2021-03-03 16:00:11,688: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 16:00:11,689: magneticAGV01 经过门 ['SK_DOOR'] checkfinishSignal error
[INFO]2021-03-03 16:00:11,730: startCharge is false
[INFO]2021-03-03 16:00:11,733: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 16:00:13,695: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 1)
[WARN]2021-03-03 16:00:13,696: magneticAGV01 经过门 ['SK_DOOR'] checkfinishSignal error
[INFO]2021-03-03 16:00:14,748: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 16:00:15,701: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 1)
[WARN]2021-03-03 16:00:15,701: magneticAGV01 经过门 ['SK_DOOR'] checkfinishSignal error
[INFO]2021-03-03 16:00:17,711: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 1)
[WARN]2021-03-03 16:00:17,712: magneticAGV01 经过门 ['SK_DOOR'] checkfinishSignal error
[INFO]2021-03-03 16:00:17,757: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 16:00:19,718: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 16:00:19,719: magneticAGV01 经过门 ['SK_DOOR'] checkfinishSignal error
[INFO]2021-03-03 16:00:20,773: magneticAGV01 (0, 0, 0, 0)
[ERROR]2021-03-03 16:00:21,226: connect AGV23 failed timed out
[INFO]2021-03-03 16:00:21,226: AGV23 checkLink failed 192.168.20.198 19204
[WARN]2021-03-03 16:00:21,226: agvThread.AGV23[tid:18324] <lock name:agv.AGV23.lock_status,<locked _thread.RLock object owner=18324 count=1 at 0x000001B3EB1F8630>> ,hold 10002 ms
[INFO]2021-03-03 16:00:21,227: name=agvThread.AGV23, pid=8432, tid=18324
[01] File "C:/Python38/lib/threading.py", line 870, in run() 
[02] File "D:/python_lx/akm/agvCtrl/agvList.py", line 565, in run() 
[03] File "D:/python_lx/akm/driver/seerAgv/agvCtrl.py", line 36, in checkLink() 
[04] File "D:/python_lx/akm/driver/seerAgv/agvApi.py", line 184, in checkLink() 
[05] File "D:/python_lx/akm/common/lock.py", line 102, in release() 
[06] File "D:/python_lx/akm/common/enhance.py", line 268, in getTrace() 
[07] File "D:/python_lx/akm/common/enhance.py", line 248, in getThreadStack()
[INFO]2021-03-03 16:00:21,724: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 16:00:21,725: magneticAGV01 经过门 ['SK_DOOR'] checkfinishSignal error
[DEBUG]2021-03-03 16:00:23,228: try connect AGV23 192.168.20.198:19204
[INFO]2021-03-03 16:00:23,730: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 16:00:23,731: magneticAGV01 经过门 ['SK_DOOR'] checkfinishSignal error
[INFO]2021-03-03 16:00:23,775: startCharge is false
[INFO]2021-03-03 16:00:23,780: magneticAGV01 (0, 0, 0, 0)
[INFO]2021-03-03 16:00:25,735: task [magneticAGV01] readIo get status  (0, 0, 0, 0, 0, 0, 0, 0)
[WARN]2021-03-03 16:00:25,735: magneticAGV01 经过门 ['SK_DOOR'] checkfinishSignal error
[INFO]2021-03-03 16:00:26,789: magneticAGV01 (0, 0, 0, 0)
